- docs/quickstart.rst
> Fix a missing backtick

- docs/writing-a-locustfile.rst
> Documentation: Update writing-a-locustfile.rst

- setup.py
a one character change :)  please review for merging.
Description:
- bumped version of requests module in setup.py to 2.9.1
- this should fix #273 and alleviate some SSL/TLS issues that have been reported
(this PR supersedes #321)
/cc @justiniso
> bump version of requests module in setup.py

- locust/stats.py
These changes were made so Failures made during a Locust run can we easily viewable. 
More information on issue [#452](https://github.com/locustio/locust/issues/452)
> Changes to consolidate errors

- setup.py
Addresses https://github.com/locustio/locust/issues/598
> Bump gevent version

- .github/ISSUE_TEMPLATE.md
- README.md
Update the text seen when creating an issue to make them more useful.
Also update README slightly to indicate this change.
> Add GH issue template and update readme

- examples/events.py
- locust/runners.py
- locust/test/test_web.py
- locust/web.py
- setup.py
The goal of this PR is to switch varying utf8 `coding`/`encoding` tags to the standard `# -*- coding: utf-8 -*-`.
> Standardize utf8 file coding declarations

- locust/static/style.css
- locust/templates/index.html
The goal of this PR is to resolve the display issues in About section of the web UI and address other outlined CSS typos in reference: #696
> Resolve improper display of About in Web UI

- locust/events.py
> Fix typo in docstring

- README.md
> Change Locust website url to https

- locust/__init__.py
This PR bumps the version string in development to 0.9.0.dev0.
> bump dev version to 0.9.0.dev0

- docs/installation.rst
This PR cleans up the installation instructions in the docs.   It also adds instructions for installing master directly from Git.
> Install instructions

- locust/templates/index.html
fixes #913 
* fix 404 error when clicking version number in 'About' box
> fix About link

- locust/static/style.css
See: https://github.com/locustio/locust/pull/938
> better horizontal scrolling

- locust/templates/index.html
> Ui headings

- locust/stats.py
- locust/test/test_web.py
- locust/web.py
> Reset exceptions and failures when stats are reset

- locust/runners.py
- locust/static/style.css
- locust/stats.py
- locust/templates/index.html
- locust/test/test_stats.py
Changed all spelling off `occurences` to `occurrences`
> Fix grammatical error in statistic reporting

- Dockerfile
- docker_start.sh
+ `docker_start.sh` script is copied inside the docker image and set as entrypoint.
> Use docker_start.sh in docker image

- .coveragerc
The goal of this PR is to resolve a breaking coverage issue from 8 months ago.
> Remove concurrency from coverage

- locust/main.py
> Revert "Exit with code 1 on greenlet exceptions"

- setup.py
Locust has been widely used for many years now, it deserves to be considered production ready in PyPi! 
It will always have bugs, and even (rarely) breaking changes, but that is part of normal development (and handled by versioning, not project status in pypi anyway).
> Let's stop calling the package beta!

- docs/conf.py
- docs/increase-performance.rst
- locust/argument_parser.py
- locust/contrib/fasthttp.py
- locust/test/test_client.py
- locust/test/test_fasthttp.py
Parameters: network_timeout, connection_timeout, max_redirects, max_retries and insecure
Also fix some test cases which used an incorrect query string.
> Support parametrization of FastHttpLocust 

- docs/retrieving-stats.rst
> Fixed typo

- examples/add_command_line_argument.py
Correct the options argument on environment
> fixed up environment.parsed_options

- docs/quickstart.rst
- docs/retrieving-stats.rst
- docs/running-locust-distributed.rst
- docs/running-locust-without-web-ui.rst
- docs/writing-a-locustfile.rst
seen these things too many times :-)
> minor typos in docs

- docs/running-locust-docker.rst
> Fixes a typo

- locust/contrib/fasthttp.py
Fix https://github.com/locustio/locust/issues/1457
> Handle http parse exceptions

- examples/use_as_lib.py
Sorry for my mistake, https://github.com/locustio/locust/issues/1542
> fix use_as_lib example

- docs/generating-custom-load-shape.rst
Comment for clarity, as per discussion in https://github.com/locustio/locust/issues/1551
> Added comment for clarity

- locust/main.py
> Only warn about open file limit when not running as master

- .travis.yml
- setup.cfg
- tox.ini
Had to wait for travis to support it...
> Run builds for python 3.9

- locust/static/chart.js
- locust/static/locust.js
This PR allow to show the number of users that are running when a metric was recorded like in the image bellow
This solve #1469
> Feature chart tooltip custom values - show user count

- locust/static/locust.js
Improve the stats data persistence and integration with new tests stats
> Stats charts data persistance

- locust/runners.py
Resolves https://github.com/locustio/locust/issues/1718
> Call shape_class.reset_time() after test_start event so that tick time is correct

- docs/testing-other-systems.rst
- examples/grpc/locustfile.py
> update grpc example, because grpc gevent issue has been fixed

- locust/runners.py
Added documentation to Runner.start_shape in reference to #1862
> Added documentation for start_shape

- locust/runners.py
- locust/test/test_runners.py
> Ensure target_user_count is set before test_start event is fired

- locust/main.py
Fix the case when locust stops with exception in headless mode with autoquit != -1
> Fix issue #1915

- docs/running-cloud-integration.rst
@cyberw
I carried out the adjustment in the documentation as requested.
Could you please validate if it is as expected?
> Fix docs issues from distributed execution with IaC

- locust/templates/index.html
- locust/web.py
PR to fix #1966.
Added 99%ile column on the Top page.
> Add 99%ile for Web UI

- locust/web.py
Fix #1995 (reverses parts of 33083d2a8adebc78fe49206025444ee9e4ecbde8)
> Reverse parts of 33083d2a8adebc78fe49206025444ee9e4ecbde8 / PR #1992

- locust/html.py
- locust/runners.py
- locust/static/tasks.js
- locust/templates/index.html
- locust/templates/report.html
Issue #1994 
A little corrected @tyge68 [fix](https://github.com/locustio/locust/commit/b14464c167da9b4939c65dbac2590e126ccaf1bd), now it seems to me more obvious the behavior that we expect in every case. Also fixed another bug: since now ratio is considered in dynamics, then after stopping ratio was considered for the case when there are no more active users, and this is clearly not what we want to see in the report.
@cyberw @eliezershindler
> Issue 1994 and static report bug

- Dockerfile
> Dockerfile: Fix permissions in venv to allow installing packages in derived images

- setup.py
Mainly to fix https://github.com/gevent/gevent/issues/1708
> Bump minimum required gevent version to 20.12.1

- tox.ini
This PR fixes CI.
See https://github.com/psf/black/issues/2964.
> Bump black version to 22.3.0

- setup.cfg
> Remove explicit version requirement for jinja2

- locust/templates/report.html
> style: add a report favicon

- locust/test/test_runners.py
As discussed in https://github.com/locustio/locust/pull/2150#issuecomment-1207437846.
> chore: Remove misleading docstring in test

- .vscode/launch_locust.json
In case user want to run locust directly from debugger
> Add example launch.json for debugging the whole Locust runtime in vscode

- locust/runners.py
change https://docs.locust.io/en/stable/running-locust-distributed.html to https://docs.locust.io/en/stable/running-distributed.html
> Fix broken link in cpu warning message.

- Dockerfile
> Bump docker base image to Python 3.10

- docs/developing-locust.rst
I have updated the documentation
> black format info is added

- locust/argument_parser.py
> Output install location and version info when called with -V 

- locust/main.py
Clarify warning messages. Fixes #2141
> Fix exception when someone sets both --headless and --autostart

- locust/static/locust.js
- locust/templates/index.html
I have added a direct link from Locust to the API indicated by the user so that the user can move directly to it
> URL link on the host name for fast navigation to the API

- locust/runners.py
Fix locustio/locust#2302 unknown worker spawning message
> Fix locustio/locust#2302 unknown worker spawning message

- locust/templates/index.html
Just a tiny helper text update that I got confused when coding. I hope it is all good, but let me know if you think I should change anything :)
> Update helper text

- locust/stats.py
RequestStats.get: Use a dict with a default value for stats entries instead of "get and then check if it was good".
Improves stats handling performance a little bit, which makes a difference in high throughput tests, because get() is called A LOT.
**CPU usage in a high-throughput test (1000rps) decreased by 10-15%**. Real world improvements are probably smaller, but not insignificant.
I did some tests with a modified fast_http_locust.py that only does a single request, and ran it against a local nginx using `time locust -f examples/fast_http_locust.py -u 100 -r 50 --headless -t 60`
w/o fix:
```
[2023-09-30 23:42:36,253] lafp-mac-7CXG.int.svenskaspel.se/INFO/locust.main: --run-time limit reached, shutting down
[2023-09-30 23:42:36,262] lafp-mac-7CXG.int.svenskaspel.se/INFO/locust.main: …
```
> Improve performance for statistics handling

- .github/workflows/tests.yml
- locust/webui/package.json
Remove typecheck from the build process and ensure the build passes on pull requests
> Remove Typecheck from Web UI Build Process and Update Github Actions

- .github/workflows/tests.yml
> update docker actions to get rid of node12 deprecation warnings

- locust/templates/index.html
> Fix pedantic typo in the index.html template

- locust/web.py
especially for http code 404 and below.
> Lower log levels for exceptions in flask

- pyproject.toml
> Use requests 2.32.2 or higher for Python 3.12

- locust/main.py
> Fix pypy gc.freeze() AttributeError

- locust/webui/src/components/LineChart/LineChart.constants.ts
- locust/webui/src/components/LineChart/LineChart.tsx
- locust/webui/src/components/LineChart/LineChart.types.ts
- locust/webui/src/components/LineChart/LineChart.utils.ts
- locust/webui/src/components/SwarmCharts/SwarmCharts.tsx
- locust/webui/src/types/ui.types.ts
1. Separate echarts configuration to separate files. This will enhance readability, ease maintainability, improve performance, and allow for proper testing (in a future ticket)
2. Expose configuration for splitting y-axis, adding areaStyle, and stacked lines
> Improve Echarts and Expose Line and Axis Configuration

- .github/workflows/tests.yml
> Update GitHub action versions

- .github/workflows/tests.yml
Fix the prerelease tag so "2.31.4.whatever" gets formatted as "2.31.4"
> Webui Fix Version Tag in NPM Prerelease Step

- package.json
This command needs to be in the package.json for the github actions
> Webui Add build lib command to package.json

- locust/dispatch.py
> Fix _kl_generator by filtering nonpositive weights

- examples/web_ui_auth.py
- locust/webui/src/pages/Auth.tsx
1. Change HTML form to a POST request
2. Read the form data in the callback
> Web UI Auth submit should submit a POST request

- locust/webui/src/components/Form/Select.tsx
- locust/webui/src/lib.tsx
1. Default values are not allowed in controlled inputs, so if we see a value is given, we should provide no default value
> Web UI Remove Default Value for Select if Value is Provided

- locust/webui/src/pages/Auth.tsx
> Web UI Auth Add Password Visibility Toggle

- locust/webui/src/components/LineChart/LineChart.utils.ts
> Webui Echarts Time Axis Should be Localized

- locust/webui/src/components/Markdown/Markdown.tsx
- locust/webui/src/components/Table/Table.tsx
This will allow us to have nicely styled links when using Markdown links in tables
> Webui Override Markdown HTML Link with MUI Link

- locust/web.py
- `auth_providers` should be a list and total should be False
> Fix Auth Args Type

- locust/runners.py
> Fix crash with older worker version requesting locustfile from master

- poetry.lock
- pyproject.toml
> Ensure we never use old version of setuptools

- locust/webui/src/components/Reports/Reports.test.tsx
- locust/webui/src/components/Reports/Reports.tsx
> Webui links should be relative

- locust/webui/src/lib.tsx
- locust/webui/src/redux/store.ts
Allows for creating a locust store with some preloaded state when using locust as a lib
> Add create store export

- locust/webui/src/pages/Auth.tsx
> Web UI: Allow Showing Only an Error Message on the Login Page

- locust/webui/src/components/Layout/Navbar/Navbar.tsx
- locust/webui/src/components/Layout/Navbar/SwarmMonitor.tsx
- locust/webui/src/components/StatsTable/StatsTable.tsx
- locust/webui/src/components/SwarmCharts/SwarmCharts.tsx
- locust/webui/src/components/Table/Table.tsx
- locust/webui/src/components/Tabs/Tabs.tsx
- locust/webui/src/components/ViewColumnSelector/ViewColumnSelector.tsx
Medium width scrollable tabs
Hamburger menu on small widths
Ensure there is always enough space in the navbar, even with a long host name
Expand hostname when there is room
> Make the Locust UI Responsive

- locust/html.py
- locust/main.py
- locust/stats.py
- locust/test/test_stats.py
- locust/web.py
So, based on #3099 discussion let's begin refactoring of main function in step by step basis.
This PR includes the following changes:
1. stats module import is simplified in all project files, with exclusion to tests.
2. stats module parameters verification is moved from main function to the end of stats module itself.
3. Small typing adjustments in stats module.
> Refactoring: Extract validate stats configuration from main function

- locust/argument_parser.py
- locust/main.py
- locust/stats.py
- locust/test/test_main.py
> Add command line option to export json results into a file

- locust/web.py
- locust/webui/src/components/SwarmForm/SwarmForm.tsx
- locust/webui/src/hooks/tests/useFetchExceptions.test.tsx
- locust/webui/src/hooks/tests/useFetchTasks.test.tsx
- locust/webui/src/hooks/useFetchExceptions.ts
- locust/webui/src/hooks/useFetchStats.ts
- locust/webui/src/hooks/useFetchTasks.ts
- locust/webui/src/hooks/useFetchWorkerCount.ts
- locust/webui/src/lib.tsx
- locust/webui/src/pages/Dashboard.tsx
- locust/webui/src/redux/api/swarm.ts
- locust/webui/src/types/ui.types.ts
> Webui: Block Submitting SwarmForm in Distributed Mode with no Workers

- docs/conf.py
> Fix Docs Config Options

- locust/web.py
- locust/webui/src/components/SwarmForm/SwarmForm.tsx
If a user types in the host field in the webui and does not enter a valid url format, show a warning
> Web UI: Always Warn of Invalid Host

- locust/main.py
> Attempt to increase open file limit (RLIMIT_NOFILE) even on master.

- locust/webui/src/components/LineChart/LineChart.tsx
One too many things were removed when optimizing the echarts dependency
> Web UI: Fix Chart Zoom Slider

- locust/test/test_web.py
- locust/web.py
Add webui support for custom argparse options that use the action="append" to build a list of parameter values.
> Support for list based custom arguments

- locust/webui/src/hooks/tests/useSortByField.test.tsx
- locust/webui/src/hooks/useSortByField.ts
> Fix useSortByField

- locust/clients.py
> Avoid exception in HttpUser if requests has lost track of the request it made

- docs/testing-other-systems.rst
- examples/socketio/socketio_ex.py
- locust/contrib/socketio.py
- locust/test/test_socketio.py
Moves on_message from SocketIOUser to SocketIOClient
> Refactor SocketIOUser to create separate SocketIOClient class

- locust/webui/src/components/Layout/Footer/FeedbackForm.tsx
- locust/webui/src/components/Modal/Modal.tsx
- locust/webui/src/components/StatsTable/StatsTable.tsx
- locust/webui/src/components/ViewColumnSelector/ViewColumnSelector.tsx
- Desktop will have the column selector on top
- Ensure the popover menu is aligned with the button
> Fix Alignment of View Column Selector
