locustio/locust

- locust/templates/index.html
Old one (@esnme) is pointing to some other weird account.
> Fixed link to ESN's Twitter page

- docs/quickstart.rst
> Fixed typo in the quickstart doc.

- docs/quickstart.rst
Document the need for `--host` argument in the quickstart.
The quickstart wasn't as quick as it could be for me, because I got errors about the missing host, and then an error about the host value missing a scheme. https://github.com/locustio/locust/issues/135 seems like the real fix, but this should at least help new locust users to get started even more quickly.
Note: do slave processes need a `--host` argument, or do they get it from the master?
> add host cli arg to quickstart

- locust/clients.py
method was set against the request response method. In the case of a POST request being redirected to GET, common on success of POSTs for login and registration. The request is incorrectly logged against the GET method for the original URL.
Closes locustio/locust#236
> changed how request_meta["method"] is set

- setup.py
Newer versions of gevent recently released to pypi seems not to work with locust
Below occurs with `gevent 1.1b4`
```
[2015-09-10 07:23:09,609] precise64/INFO/locust.main: Starting web monitor at *:8089
[2015-09-10 07:23:09,611] precise64/ERROR/stderr: Traceback (most recent call last):
[2015-09-10 07:23:09,611] precise64/ERROR/stderr: File "/usr/local/bin/locust", line 9, in <module>
[2015-09-10 07:23:09,611] precise64/ERROR/stderr:
[2015-09-10 07:23:09,612] precise64/ERROR/stderr: load_entry_point('locustio==0.7.3', 'console_scripts', 'locust')()
[2015-09-10 07:23:09,612] precise64/ERROR/stderr: File "/usr/local/lib/python2.7/dist-packages/locust/main.py", line 437, in main
[2015-09-10 07:23:09,612] precise64/ERROR/stderr:
[2015-09-10 07:23:09,613] precise64/ERROR/stderr: …
```
> Lock gevent version

- locust/static/locust.js
"if (report.slave_count)" returns false when value is 0, so the UI doesn't update when all slaves are disconnected.
> [#62] Correctly update slave count when drops below 1.

- docs/extending-locust.rst
The handler argument names are incorrect in the example listed in the documentation, which caused me some confusion and debugging. The official event hook documentation has the correct names - but this example has incorrect parameter names.
> Fix handler argument names.

- docs/changelog.rst
- locust/__init__.py
- setup.py
@heyman let me know if I'm missing anything. I tried to diff from the last version, but the tag was missing. 
re: https://github.com/locustio/locust/issues/407
> Release updates for v0.7.4

- locust/runners.py
Fixes 'locust --slave' so that it works with Python 3.
> Python 3 compatibility for slave mode. (Fixes 'locust --slave')

- docs/writing-a-locustfile.rst
When this rst is converted to html, the "--host" becomes "–host". This change fixes that with an inline code block.
> Fix document bug concerning '--host' option.

- locust/stats.py
Fixes logging during locust hatching when using --no-web with Python 3.
(previously a "ImportError: No module named 'runners'" error is raised and no logging occurs)
> Python 3 compatibility with --no-web option

- locust/clients.py
This seems to be the only place in the code where you're not calling super() to init the superclass. With this change, HttpSession can participate in diamond class patterns which I have a specific use case for (integrating with requests_oauthlib).
> Use super() for HttpSession init call

- docs/quickstart.rst
- docs/writing-a-locustfile.rst
this is an attempt to addresses #500
---
Push for the following norm: all module imports either reference
installed modules, or modules beneath the "project root" (i.e. the CWD).
To that end, remove any examples where the locustfile is not beneath the
CWD.
Also, provide some example project directory structures.
> docs: clarify locust invocation norms

- .travis.yml
- README.md
- setup.py
- tox.ini
Adds Python 3.6 to the travis/tox build process.
Additionally, this PR introduces the use of a `matrix` in the travis pipeline to run each env with it's specific image.
> Python 3.6

- locust/web.py
This change limits the number of rows on the web UI to display at most **500** rows in the `stats` and `failures` tabs. A common scenario is the app failing under load, resulting in a large number of unique failures, bringing the rendering to a halt. 
A simple locustfile demonstrates the issue:
```python
import random 
from locust import HttpLocust, TaskSet, task
class UserTasks(TaskSet):
@task
def error(self):
self.client.get("/404/{}".format(random.randint(0,99999999999))
class WebsiteUser(HttpLocust):
min_wait = 0
max_wait = 0
task_set = UserTasks
```
This will generate a large number of results and errors, eventually killing the page. I feel that 500 results is a reasonable number to display as it's more than anyone could consume manually through the web UI. But for automated …
> Truncate number of errors displayed in the web UI

- locust/templates/index.html
It wasn't clear to me what units were being displayed in the table. Assuming it was milliseconds and adding it the table so it's clear. Thoughts?
> Add units to table

- locust/main.py
Fixes #138
This PR prohibits naming your locustfile `locust.py`, which previously caused Locust to exit with a misleading message ("No Locust class found").
The new behavior is to exit with a more helpful error message explaining not to name the file `locust.py`. 
The issue was occuring because the locustfile gets imported as a Python module (with the .py extension removed).  So naming it `locust.py` caused a namespace clash with the internal `locust` module, which would get re-imported instead of the locustfile.
Note: This only fixes the common case where you have named it `locust.py`.  There are also other reserved names that can not be used as locustfile names.  We might want to add something to the docs to explain this.
> Prohibits the locustfile from being named 'locust.py'

- examples/custom_xmlrpc_client/server.py
- locust/clients.py
- locust/core.py
- locust/rpc/socketrpc.py
- locust/test/test_client.py
- locust/test/test_locust_class.py
- locust/test/test_main.py
- locust/test/test_runners.py
- locust/test/test_stats.py
- locust/test/test_web.py
- setup.py
This PR removes unused imports and exception assignments throughout the project.
*Removed whitespace trimming per @cgoldberg's request.*
> Remove unused imports

- locust/stats.py
Address #399, which is the same issue we just hit in our usage.
The counter is incremented in `log` but it was being checked for the end condition before that point was hit.
This meant that if you ran 3 requests using the command line mode:
```
locust --no-web -c 1 -r 1 -n 3 -f tornado_nats_locust.py
```
you would end with Locust actually executing 4 tasks.
FYI @cgoldberg @heyman @seangerhardt-wf
> Fix off by 1 error in stats.py resulting in additional request always being off

- README.md
I don't think there are nice "badges" for slack the way there are for gitter.
I didn't remove that link either, is the goal here to replace gitter with Slack?
@heyman
> Add slack signup link to readme

- locust/static/style.css
- locust/templates/index.html
- locust/web.py
Adds the host url to the header:
PR #295 does the same thing slightly differently but failed tests and is over a year old so created my own (with less css changes as displaying it with the existing header items keeps the UI more visually consistent).
The max width and word wrap have been set to prevent long urls ruining the layout of whole header.
> Adds host name to the header

- locust/main.py
Summary:
- removed limitation to not have --no-web together with --master
- added --expect-slaves option to tell how many slaves expected to connect
- on all expected slaves are connected, master initiates hatching
Taurus mailing list discussion for reference: https://groups.google.com/forum/#!topic/codename-taurus/Gs3VdphRSjo
> Allow --no-web together with --master for automation

- docs/quickstart.rst
Copying and pasting the command to get help into the console fails because of a formatting issue that combines the double dashes into a single dash.
> Fix formatting issue combining double dashes into single dash

- docs/index.rst
- docs/using-other-languages.rst
Now, we are able to write test scenarios in golang.
add @cgoldberg as a reviewer.
> Added introduction of Boomer

- docs/quickstart.rst
- locust/main.py
- locust/stats.py
- locust/web.py
- setup.py
I started reviewing https://github.com/locustio/locust/pull/445 but found that it had enough problems that it'd be just easier to rewrite the entire PR.
This:
- Ability to write csv files for both the requests and distribution csv as a command line flag
- Refactored the logic in the web handler to reuse this csv generation for better portability
I also fixed #598 because that issue has been annoying me for a while.
> Add ability to write csv stats files  

- docs/conf.py
- examples/basic.py
- examples/custom_xmlrpc_client/server.py
- examples/custom_xmlrpc_client/xmlrpc_locustfile.py
- examples/events.py
- locust/cache.py
- locust/clients.py
- locust/core.py
- locust/inspectlocust.py
- locust/log.py
- locust/main.py
- locust/rpc/protocol.py
- locust/rpc/socketrpc.py
- locust/rpc/zmqrpc.py
- locust/runners.py
- locust/stats.py
- locust/test/test_client.py
- locust/test/test_locust_class.py
- locust/test/test_main.py
- locust/test/test_runners.py
- locust/test/test_stats.py
- locust/test/test_taskratio.py
- locust/test/test_web.py
- locust/test/testcases.py
- locust/web.py
- setup.py
The goal of this PR is to sort all Python imports for readability in the following order:
- Future
- Python Standard Library
- Third Party
- Current Python Project
- Explicitly Local (. before import, as in: from . import x)
- Custom Separate Sections (Defined by forced_separate list in configuration file)
- Custom Sections (Defined by sections list in configuration file)
You can automatically format your Python imports with the package `isort`.
> Sort all Python imports

- .travis.yml
- docs/installation.rst
- examples/vagrant/vagrant.sh
- locust/web.py
The goal of this PR is to migrate from `libevent` to `libev` and from gevent's `wsgi` module to `pywsgi` .
- Addresses #649
> Modify gevent wsgi and libev dependencies

- docs/changelog.rst
- locust/__init__.py
@heyman  @cgbystrom  @cgoldberg 
This updates the version, however I cannot release the version to pypi (see [this request](https://github.com/locustio/locust/issues/628)).
Once this PR is merged, please also upload to pypi so that people can begin consuming.
FYI  @mbeacom
> Bump version to 0.8a3 for another pre-release candidate

- locust/main.py
if the `locustfile.py` file is located in the filesystem root, and the `locust` command is launched from the fs root too, then the file is not found.
(to work around this issue, `-f /locustfile` has to be explicitly passed to the `locust` command)
having the locustfile in the fs root is a common use case when running in docker
> find locustfile in the root directory

- locust/main.py
- locust/runners.py
- locust/test/test_parser.py
Do not reset statistics on hatch complete unless the user specifically chooses to. Added a `--reset-stats` option to force a reset, which inverts the meaning of the older `--no-reset-stats` option. Deprecated the `--no-reset-stats` option, but continue to allow it for backwards compatibility.
Closes #672
> Do not reset statistics on hatch complete 

- docs/writing-a-locustfile.rst
While browsing docs noticed in one doc small Python3 incompatibility. Switched to using `print()` as function call vs as statement
> Small python 3 syntax improvement in docs

- .coveragerc
- .travis.yml
- Makefile
- README.md
- tox.ini
The goal of this PR is to add automated coverage reports via https://codecov.io/
- Eventually needs repo owner to configure the integration at:  https://github.com/integration/codecov
- Configure GitHub policy to allow or deny contributor ability to override the integration PR enforcement in the event of a decrease in coverage
> Add codecov integration

- docs/changelog.rst
- docs/installation.rst
- locust/__init__.py
- setup.py
The goal of this PR is to merge the 0.8 branch that seems to have cut the latest locust release, but hasn't been merged to master.
We'll want to merge this and release a new pypi package from `master`.
> Merge 0.8 branch.

- docs/third-party-tools.rst
Locust4j is a load generator for locust, written in Java.
Now, we can write test scenarios in Java.
> added introduction to Locust4j

- locust/main.py
error message referred to `--time-limit`.  This PR changes it to `--run-time`.
> fix error message on invalid time format

- locust/static/locust.js
- locust/web.py
This ensures that all json responses have the correct mimetype without needing
the extra boilerplate to set the content-type header.
This helps let extensions like JSONViewer do the right thing when examining JSON responses like `/stats/requests`
> Use flask.jsonify for json responses

- locust/static/locust.js
- locust/templates/index.html
Small change to add clarity to the chart.
> Adding unit to Response Time chart

- docs/quickstart.rst
- docs/writing-a-locustfile.rst
- locust/core.py
- locust/events.py
- locust/main.py
- locust/runners.py
If a TaskSet has an `on_stop` method, it will be run before the process exits. It will also look for a property on the class named `always_run_on_stop`, which if True will run regardless if the `on_start` method finished.
Looking to solve #59 
Any comments on this functionality?
> Adds support for setup, teardown, and on_stop methods

- .gitignore
- Makefile
- setup.py
- tox.ini
As locust no longer support Python 2.6, there is no need to install unittest2. The unittest shipped with the Python 2.7+ stdlib is the same as unittest2.
Results in fewer dependencies and slightly faster installation during testing.
Python support was removed in version 0.8.
> Remove test dependency unittest2

- docs/writing-a-locustfile.rst
- locust/clients.py
- locust/test/test_web.py
`response.content` is a byte string. It should be compared against other byte strings. To examine the response content as text, use the `response.text` attribute.
Fixes warnings when Python is passed the `-b` argument (Issue warnings about `str(bytes_instance)`, `str(bytearray_instance)` and comparing bytes/bytearray with str.)
```
BytesWarning: str() on a bytes instance
```
For additional information on the `-b` argument, see:
https://docs.python.org/3/using/cmdline.html#cmdoption-b
For additional information on response.text, see:
http://docs.python-requests.org/en/master/api/#requests.Response.text
> Fix bytes/text confusion with response objects

- tox.ini
The dependency pyzmq is listed in `setup.py`. Tox will install all package dependencies by default. The dependencies do not need to be respecified in `tox.ini`. Remove the redundant dependency specification.
> Update tox.ini so as to not respecify package dependency pyzmq

- tox.ini
The environment variables, `CI` `TRAVIS` `TRAVIS_*` `TOXENV`, do not influence locust nor its tests. Keep the tox configuration minimal by excluding them. Avoids any future unexpected differences between CI and local test runs.
> Remove unused environment variables form tox configuration

- docs/index.rst
this PR enhances the docs by:
* expands the index page entries in the Documentation
* re-orders the index so changelog is after third party tools
expanding the index is a huge improvement (IMO).
> expand and re-order documentation index

- docs/retrieving-stats.rst
Provide an example in the docs based on  [this Stack Overflow question](https://stackoverflow.com/questions/49197829/locust-test-statistics-meta-data/49198304#49198304).
> Docs: update test statistics page with example responses

- docs/api.rst
- docs/quickstart.rst
- examples/custom_wait_function.py
- locust/core.py
- locust/test/test_locust_class.py
Most real-world inter-arrival times are exponentially distributed so it would be nice to be able to model that using locust. I've added the possibility for a user-defined wait_function, so *any* desired inter-arrival time can be modelled. Added some [examples](https://github.com/ps-george/locust/blob/df89db25a3444bc41a5c00b252f581156e80f405/examples/custom_wait_function.py) of exponential wait times I'd like to be able to model. If `wait_function` is not set, it will default to exactly as before, i.e. `random.randint(self.min_wait,self.max_wait)`
Change-log needs updating if merging this.
> Added user-defined wait_function to locust and TaskSet

- locust/test/testcases.py
Support for Python 2.6 was removed in 33a9a1a7da509d1202bf0787c9f0ead6b4aa12f5. As it is no longer supported, can remove compatibility workarounds that were put in place to Python 2.6's outdated unittest.
> Remove compatibility workarounds for Python 2.6

- docs/installation.rst
- docs/quickstart.rst
- docs/retrieving-stats.rst
- docs/running-locust-without-web-ui.rst
- docs/writing-a-locustfile.rst
Also removed some trailing whitespace
> docs: Syntax highlight code and commands

- .travis.yml
- README.md
- docs/installation.rst
- locust/test/test_web.py
- setup.py
- tox.ini
* Dropping support for python 3.3 as discussed in #799 
* Fixing test_web.py, wsgi has been superceded with pywsgi
> Drop Python 3.3 support

- locust/static/locust.js
- locust/templates/index.html
Fixes #149
When using proxy or exposing Locust UI in Kubernetes (via ingress) the URLs get prefixed (for example, served under http://domain.com/locust instead of http://domain.com).
On the other hand, links in html template and JS (rest calls) are absolute (starting with '/') which makes the UI inoperable.
This PR makes the links relative - they work fine both with and without a prefix.
To validate:
```
git clone https://github.com/karol-brejna-i/locust.git
git checkout origin/149_url-prefix-for-web-ui
pip3.6 uninstall locustio -y 
pip3.6 install ./locust/ 
locust -f locust/examples/basic.py --host=http://localhost:8089
```
When looking at HTML page sources you should see `<link rel="stylesheet" type="text/css" href="./static/style.css?v=0.8" media="screen">` somewhere at the beginning …
> Make UI URL links relative

- docs/api.rst
- docs/writing-a-locustfile.rst
- examples/browse_docs_sequence_test.py
- locust/__init__.py
- locust/core.py
- locust/test/test_task_sequence_class.py
This pr is related to [this issue](https://github.com/locustio/locust/issues/311).
As I said In slack, I know there is an easy workaround of defining only one task in the TaskSet and defining all the behavior there. The problem with the workaround is that it is a bit hacky, since you have to do `self.wait()` whenever it's needed instead of letting the framework handle it.
Introduce a new class: `TaskSequence` which accepts a new decorator @seq_task(int) to define the order of the tasks.
For example:
```python
class BrowseDocumentationSequence(TaskSquence):
def on_start(self):
self.urls_on_current_page = self.toc_urls
@seq_task(1)
def index_page(self):
r = self.client.get("/")
pq = PyQuery(r.content)
link_elements = pq(".toctree-wrapper a.internal")
self.toc_urls = [
l.attrib["href"] for l …
```
> Add tasks sequence support

- setup.py
msgpack-python has been renamed to msgpack.
Closes #837
> Change name of msgpack dependency.

- locust/clients.py
Tiny doc change - The Requests module's docstrings mention that `timeout` should be in seconds, but it's unclear here.
> Specify seconds for the `timeout` parameter

- Makefile
This allows developers to build the project without publishing it to pypi.
Also add the -f tag to the cleanup bit so it doesn't bail when `dist/` is missing.
> Separate release into build and release steps

- locust/rpc/protocol.py
- locust/test/test_task_sequence_class.py
this PR fixes 2 deprecation warnings:
* `/locust/rpc/protocol.py:15: PendingDeprecationWarning: encoding is deprecated, Use raw=False instead.`
* `/locust/test/test_task_sequence_class.py:72: DeprecationWarning: Please use assertEqual instead.`
> Fix deprecation warnings

- Makefile
This PR updates the `Makefile` so `make build` command will also create a wheel for distribution.
see: https://pythonwheels.com/
> update Makefile so build also creates a wheel

- docs/api.rst
- docs/changelog.rst
WARNING: Title underline too short.
WARNING: Title overline too short.
> Fix Sphinx build warnings

- .travis.yml
- Dockerfile
- docker_start.sh
- docs/running-locust-distributed.rst
- docs/running-locust-docker.rst
- examples/docker-compose/docker-compose.yml
- tox.ini
After talking with @JDiPierro I'm taking over this initiative. However I can't actually interact with the old PR so this is being created. His original work has been rebased onto latest master.
Referencing #849 
Adds a basic `Dockerfile` with a base of `python:3.7-alpine` putting final image size at 291MB. 
I believe most if not all of the changes requested by @mbeacom have been addressed in this as well.
> Official Docker image and documentation V2

- locust/runners.py
Fixes #894 
Current implementation collides easily in environments with large number of slave processes on the same host starting at the same time.
> Use uuid4 to generate slave client_id

- locust/static/style.css
Fixed #903 to allow requests/sec UI column to display. Currently styling seems to allow min browser width of 1125px+ without clipping column now.
> Fixed #903 to allow requests/sec UI column to display.

- docs/writing-a-locustfile.rst
Based on a simple test, it looks like when no locust class is specified on CLI execution, spawns pull from the full set of defined locusts.  This PR just clarifies that behavior.
> clarifying locust class usage when no classes specified on CLI

- MANIFEST.in
The locustio sdist doesn't actually include the LICENSE:
```
$ curl https://files.pythonhosted.org/packages/e6/88/2d56405c715df8c4c94850857c581007d39fe50dfe9dbcac91e378a8f24f/locustio-0.9.0.tar.gz -L | tar tz | grep LICENSE
$
```
This fixes #788.
> Include LICENSE in the sdist.

- locust/test/test_runners.py
I am not sure why mock is imported multiple times but the tests pass even without them. If there is a good reason to keep them then this could be closed. Otherwise for readability I think they should be removed.
> Remove repeated imports of mock

- locust/test/test_task_sequence_class.py
The default min and max wait time between tasks result in these two tests taking a combined ~6 seconds of run time. With these new values the total run time for the entire test suite is reduced by about 68%.
> Speed up task sequence tests

- locust/static/style.css
I can't see the last column in the stat table when the name is long. So I think locust web should support the horizontal scrolling on the stats table.
> Support horizontal scrolling for the stats table

- .coveragerc
- locust/main.py
- locust/rpc/zmqrpc.py
- locust/runners.py
- locust/test/test_runners.py
- locust/test/test_zmqrpc.py
I have noticed some issues bringing up master and slave nodes within Kubernetes. I noticed in some other github issues for Locust that some of the issues may be solved by adding a heartbeat between the nodes.
The changes include the addition of a heartbeat thread on the master. The slaves check in with the master by means of their own heartbeat worker thread. There is also a new state (missing) that will show in the UI if a slave fails to check in with the heartbeat to the master.
I also think that it prevents some stale state by having the slaves also send their current state to the master. Reason being that if a slave fails to check in and goes missing, how else would the master know what the slave is doing after it continues to check in.
I got my inspiration from the ZMQ guide, …
> Add heartbeat to detect down slaves

- .github/ISSUE_TEMPLATE.md
- README.md
This PR removes the wording from `README.md` and `ISSUE_TEMPLATE.md` that references submitting feature requests.
> remove references to submitting feature requests

- CHANGELOG.md
- docs/changelog.rst
- locust/__init__.py
Should be more straightforward this time.
The auto changelog reordered some things but left them all present.
@cgbystrom @heyman @cgoldberg
> Update change logs & release 0.10.0

- locust/rpc/zmqrpc.py
- locust/util/exception_handler.py
When I'm running Locust in distributed mode, I've noticed an exception thrown from slave agent "AssertionError: Only one greenlet can be waiting on this event".
On investigating this issue, I find out that there're multiple greenlets in SlaveLocustRunner as shown in https://github.com/locustio/locust/blob/87a9aa1cb937c68e4456cafd23f3c42f25023931/locust/runners.py#L384-L388
and they're talking to Locust master with the same zmq socket, so there might be concurrent calls to self.client.send, then the exception above will be thrown.
We can leverage semaphore to avoid the concurrent calls, but there will be a performance cost. Since these concurrent situations are not very likely, it's better to simply add a retry for socket communication and makes Locust more robust.
> add retry in zmqrpc

- locust/rpc/zmqrpc.py
- locust/test/test_zmqrpc.py
From zmqrpc.py, there're two new added methods send_to_client and recv_from_client for the messaging with client.
https://github.com/locustio/locust/blob/87a9aa1cb937c68e4456cafd23f3c42f25023931/locust/rpc/zmqrpc.py#L14-L27
In method send_to_client **msg.node_id** is supposed to be a str object, while in the context of zmqrpc **msg.node_id** will be assigned with the **addr** from the return tuple of recv_from_client, which was a bytes object.
This consistency will cause the encoding issue of **addr** where it's referenced, including the example below            https://github.com/locustio/locust/blob/87a9aa1cb937c68e4456cafd23f3c42f25023931/locust/web.py#L126-L134 
the **slave.id** is also assigned with **addr** and it will be a bytes object which will cause an exception thrown from …
> fix inconsistency in zmqrpc

- locust/__init__.py
- locust/runners.py
Fixes https://github.com/locustio/locust/issues/981
> Add "stopping" state.

- locust/stats.py
- locust/templates/index.html
- locust/test/test_web.py
- locust/web.py
#675 Download the "failures" tab from the web ui as a csv file
> Add failures csv download

- locust/main.py
Fixes #560. Give an option to disable it. It's probably too late to change the functionality to an opt-in, but exit codes should only post if there's actually a problem with the binary, not because there was an error in a test.
> Add command line argument to specify exit code on response errors

- examples/semaphore_wait.py
Module has changed to `gevent.lock` from `gevent.coros`
> Fix for the examples regarding semaphore_wait.py

- examples/custom_xmlrpc_client/server.py
Discovered via: __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
> Use print() function in both Python 2 and Python 3

- .travis.yml
__sudo: required__ no longer is...  [Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
"_If you currently specify __sudo:__ in your __.travis.yml__, we recommend removing that configuration_"
> Travis CI: The sudo tag is now depricated in Travis CI

- docs/quickstart.rst
- locust/core.py
- locust/test/testcases.py
See this for details, https://github.com/locustio/locust/issues/1044
> stop looking for proxy settings

- .travis.yml
- README.md
- docs/installation.rst
- setup.py
- tox.ini
This PR drops Python 3.4 support from our testing and documentation.  Nothing here actually breaks compatibility with Python 3.4, but this removes it from our tests (tox tests, travis-ci matrix), the setup.py classifier, and all references in the docs.
Python 3.4 has been deprecated for several months by the Python Core maintainers, newest versions of pip no longer work with it, and new versions of gevent have already dropped python 3.4 support.
> drop Python 3.4 support

- locust/stats.py
- locust/test/test_stats.py
Following up after the conversation in this PR: https://github.com/locustio/locust/pull/1075
Code changes as suggested in disucssion. Requesting review @aldenpeterson-wf  @cgoldberg
Added unit tests.
EDIT: force push after removing whitespace changes and rebasing onto latest master.
> Fix error percentage cli output

- locust/test/test_util.py
- locust/test/test_web.py
- locust/util/rounding.py
- locust/web.py
> Min and max response times rounded to nearest int in web view

- Dockerfile
A simple PR to change the Dockerfile to use a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/). This reduces docker image size from 286MB to 127MB.
> Using docker multi-stage for 50% smaller image

- docker_start.sh
- docs/running-locust-docker.rst
In this PR I am:
- Adding a new env var so users can pass options to `locust` in docker image. This means `standalone` mode with no web is now possible. Great for running as k8s `Job`.
- Updating docker documentation with new `LOCUST_OPTS` env var and a couple extra examples for how to run your tests.
Does it make sense? Is that OK?
> Allow options to be passed to locust in docker, update docs

- Dockerfile
Installs from the local code rather than a release version, creates a non-root user, and switches from entrypoint to cmd for better customization.
> Improvements for Dockerfile

- locust/contrib/fasthttp.py
- locust/test/test_fasthttp.py
This is a potential fix for a bug that causes the content to be "dropped" when passing `catch_response=True` in combination with `FastHttpLocust`.
To recreate, run following locust-file with locust v0.12.0:
```python
from locust import TaskSet, task
from locust.contrib.fasthttp import FastHttpLocust
class ExamplePage(TaskSet):
@task
def index(self):
with self.client.get("/", catch_response=True) as r:
print(r.content)
class AwesomeUser(FastHttpLocust):
task_set = ExamplePage
host = "http://example.com"
```
Inside [`ResponseContextManager.__init__`](https://github.com/locustio/locust/blob/master/locust/contrib/fasthttp.py#L318) the responses `__dict__` is copied over, but for some reason the content doesn't tag along...
To be honest, I'm still not entirely sure why it gets dropped, might …
> Fix empty bytearray(b'') returned when using catch_response=True

- .travis.yml
- README.md
- docs/installation.rst
- setup.py
- tox.ini
Python 3.8 was released on October 14th, 2019.
> Add Python 3.8 to the test matrix

- .travis.yml
'dist: xenial' is now the default.
> Remove 'dist: xenial' from Travis configuration

- locust/main.py
- locust/test/test_parser.py
- locust/test/test_web.py
The Python module optparse is deprecated and is no longer receiving updates. From the [Python documentation](https://docs.python.org/3/library/optparse.html):
> Deprecated since version 3.2: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.
Can take advantage of the argpares API by making the following cleanups:
---
Remove `default=None`. It is the default.
https://docs.python.org/3/library/argparse.html#default
> The default keyword argument of add_argument(), whose value defaults to None, ...
---
Remove `dest='...'`, when it matches the first long option, which is the argparse default.
https://docs.python.org/3/library/argparse.html#dest
> For optional argument actions, the value of `dest` is normally inferred from …
> Switch from using optparse to argparse for command line arguments

- locust/web.py
Fixes the plot when there are too many unique urls.
#1059 
#889 
The total stats block, which is usually located at the end of the list of stats, was getting truncated whenever there were too many URLs that were being requested.  Here I add the total stats back to the end of the report.
> Fixed issue with Total Requests Per Second plot

- locust/__main__.py
- locust/main.py
Allows executing locust as a module using the command:
$ python -m locust
https://docs.python.org/3/library/__main__.html
> Add __main__.py file

- locust/runners.py
- locust/test/test_runners.py
This should fix #848 and is an alternative implementation to #860. It's simpler but less sophisticated.
With this PR one could still get an uneven distribution  of Locust classes when killing locusts. For example if one has multiple Locust classes and then kills a single user one by one by changing the number of locusts multiple times and decreasing the number by one each time. I don't think this is a big issue. It could be fixed later by rewriting the logic of the `LocustRunner.kill_locusts()` method to - instead of using `weight_locusts()` to get a list of classes to remove - use `weight_locusts()` to  get a list of the new distribution and then diffing the current distribution to the new one and killing the locusts needed to achieve the new distribution.
> Fix rounding error when spawning users from multiple locust classes

- tox.ini
Blocked by #1038  https://travis-ci.org/locustio/locust/jobs/550766994#L274
> Tox: Add flake8 tests to find Python syntax errors and undefined names

- locust/static/style.css
- locust/templates/index.html
This PR removes the `table-layout: fixed` CSS property from the  stats table in the web UI, in order to make better use of the available space.
The `table-layout:fixed` property was added by #962 (which is a PR for #938), so this PR will partly revert those changes. However I'm still able to see the whole table by scrolling the page horizontally after these changes.
**Before:**
**After:**
> Table layout fix to use available space better

- locust/templates/index.html
- locust/test/test_web.py
- locust/web.py
URL names (for stats) were not HTML-escaped in the dashboard.
This made names with angle brackets disappear. For example:
```
self.client.get(url, name='/some-resource/upload/<uuid>')
```
would show up as `/some-resource/upload/` instead of `/some-resource/upload/<uuid>` which is confusing.
I added new key to /stats/request - "safe_name" - so that escaping
is on the server side and javascript has less logic.
> Escape HTML entities in endpoint names #374

- locust/stats.py
- locust/test/test_runners.py
- locust/test/test_stats.py
> Allow None response time for requests

- docs/writing-a-locustfile.rst
> fix self.client call in code examples

- locust/log.py
Calling `isatty()` on `sys.stderr`/`sys.stdout` inside locust will currently raise an exception (AttributeError: 'StdOutWrapper' object has no attribute 'isatty'), this PR just makes it so that it definitely identifies itself as not being connected to a tty.
> Make stdout/stderr wrappers identify themselves as not being a tty

- locust/clients.py
- locust/test/test_client.py
* currentlly there is option to group urls name for dynamic endpoint
* adding name parameter to request
* this commit group error messages for dynamic endpoints
* if name parameter was provided
> Add errors grouping for dynamic endpoint

- locust/core.py
- locust/test/test_runners.py
I discovered a bug introduced in the last commit on stop-timeout. Adding a test case for it (and once you have seen that it actually fails), I will revert that commit to show that it now works :)
> Fix and add test for when locusts fail to exit at end of iteration during stop timeout.

- locust/templates/index.html
- locust/web.py
It works like https://github.com/locustio/locust/pull/593/commits/0e285ccaf50fee99e8eda8c4732e643ce88d2771
known issues:
1. because the response time greater than 100ms is rounded, when calculate response time percentile from response_times, the result may be greater than the max response time.
> add 90th %ile to the stats page

- locust/clients.py
- locust/test/test_client.py
minor update for build_url function in HttpSession 
related to issue:
https://github.com/locustio/locust/issues/1133
> update build_url function in Locust HttpSession 

- locust/contrib/fasthttp.py
> Fix AttributeError: 'CompatRequest' object has no attribute 'type' in Cookiejar

- locust/clients.py
- locust/contrib/fasthttp.py
- locust/events.py
- locust/stats.py
- locust/test/test_fasthttp.py
- locust/test/test_locust_class.py
- locust/test/test_stats.py
Like with request_success... This breaks compatibility with existing tests that use event handlers with positional arguments. Maybe it is worth a bumped minor version, to indicate that to users.
> Add response_length to request_failure event

- locust/clients.py
- locust/test/test_client.py
Reverts locustio/locust#1134
Unfortunately, I've found a big disadvantage of this change:
`urljoin` from `urllib` has a surprising behavior: it cuts everything in base url after "/", if the second part of url to join starts from "/".
For example, `urljoin("http://mysite.com/api/v0", "/path/to/join")" returns a result:
`http://mysite.com/path/to/join`
It will lead to a lot of issues and errors in all existing locust tests where combined base url is used.
The only option I see is to revert this change. Sorry for inconvenience.
> Revert "update build_url function in Locust HttpSession "

- Dockerfile
If the user doesn't have a home directory then `pip install --user xxx` fails as there's nowhere to write to.
Resolves https://github.com/locustio/locust/issues/1149
> Docker: add home directory for locust user to install pip packages

- docker_start.sh
exec used to start so from now, it will be the top process and can handle the SIGTERM messages.
> Allow locust to get SIGTERM(aka Ctrl+C) messages.

- locust/static/chart.js
I find myself taking screenshots of the charts quite often, this adds a small button in the top right corner of the charts for downloading them as PNG images.
> Add toolbox control for for downloading chart as png

- docs/quickstart.rst
- locust/main.py
- locust/test/test_parser.py
- locust/test/test_web.py
- locust/test/test_zmqrpc.py
- setup.py
> Use ConfigArgParse instead of argparse, to support getting parameters from config file and/or env vars.

- docs/retrieving-stats.rst
- locust/main.py
- locust/stats.py
- locust/templates/index.html
- locust/test/test_stats.py
- locust/test/test_web.py
- locust/web.py
Adds --csv-append flag to enable appending of the metrics to CSV log file (`locust_stats_distribution`).
It allows for tracking changes in response times over the course of long test runs.
> Stats: New argument "--csv-full-history" appends stats entries every interval in a new "_stats_history.csv" File

- locust/main.py
- locust/runners.py
- locust/templates/index.html
- locust/test/test_runners.py
- locust/test/test_web.py
- locust/web.py
This PR adds a new feature related to the issue: #1001 
The main idea is to allow you to trigger a load test in Step Load pattern, and you can specify a Step Clients and a Step Duration to monitor your server's performance with different user load.
For example if you specify the swarming plan with 
`Total Clients of 50, Hatch Rate of 1, Step Clients of 5 and Step Duration of 5m`
click the button and it will trigger a load test with increasing the user load by 5 every 5 mins.
At last you will get the metrics charts as below after 1h' running:
> Support Step Load Pattern

- locust/stats.py
Using `--csv` flag in `0.13.3` version of locust (after https://github.com/locustio/locust/pull/1146 was merged) only prints percentiles in the sliding window of `CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW`. This happened because instead of using `get_response_time_percentile()` function i used `get_current_response_time_percentile()` in `requests_csv()` function.
> Use `response_time_percentile` for <name>_stats.csv file instead of `current_response_time_percentile`

- locust/contrib/fasthttp.py
> Get encoding from content-type header instead of autodetecting using chardet (which is slow)

- locust/contrib/fasthttp.py
> Send Accept-Encoding: gzip, deflate as default in FastHttpLocust.

- locust/core.py
- locust/test/test_old_wait_api.py
- locust/test/test_runners.py
- locust/util/deprecation.py
I know this is a deprecated feature, but here's a fix anyways.
> Allow min_wait and max_wait times of 0

- locust/contrib/fasthttp.py
maybe @mbeacom or @skivis has feedback on this? Particulary regarding the original change that was made to fix #1193
> Allow users to override encoding when decoding requests (maybe using chardet, as was the default before)

- docs/running-locust-docker.rst
The link was in Markdown, rather than reStructuredText.
> Fix link formatting for the Helm chart

- docs/index.rst
Without this, the only way to find the page is by either search, or happening on the link at the bottom of "Running Locust distributed".
Luckily, Google had indexed the page despite not being in the TOC, or I'd have never seen it.
> Add "Running Locust with Docker" to the TOC

- locust/stats.py
- locust/test/test_stats.py
> Save failures.csv in --no-web mode

- .travis.yml
- docs/changelog.rst
- docs/installation.rst
- locust/__init__.py
- setup.py
- tox.ini
Future releases will just not show support for these versions (so they wont be installed by pip), but this way we can show users what to do instead of just giving them an old package.
Solves #1120
> Drop support for pre 3.6 Python versions (give error during installation)

- Dockerfile
- docs/running-locust-distributed.rst
- locust/main.py
I remove the description of port 5558.
locust hadn't bind two sockets since from #927
> docs: remove the description of port 5558

- README.md
- locust/clients.py
- locust/contrib/fasthttp.py
- locust/core.py
- locust/inspectlocust.py
- locust/main.py
- locust/runners.py
- locust/stats.py
- locust/test/test_fasthttp.py
- locust/test/test_locust_class.py
- locust/test/test_stats.py
- locust/test/test_task_sequence_class.py
- locust/test/test_web.py
- locust/test/testcases.py
- locust/util/deprecation.py
- locust/web.py
- setup.py
> Remove six and other 2.7 compatibility code

- locust/core.py
> Fix simple typo: betwen -> between

- locust/core.py
- locust/test/test_locust_class.py
Give the user gets a better exception than `IndexError: Cannot choose from an empty sequence`
Should help with user problems like this one for instance https://stackoverflow.com/questions/60629518/error-while-executing-basic-code-in-locust
> Give a more descriptive error when the Locust or TaskSet has no tasks.

- docker_start.sh
- docs/quickstart.rst
- docs/running-locust-distributed.rst
- docs/running-locust-docker.rst
- docs/running-locust-without-web-ui.rst
- docs/third-party-tools.rst
- examples/docker-compose/docker-compose.yml
- examples/events.py
- examples/vagrant/supervisord.conf
- locust/argument_parser.py
- locust/env.py
- locust/event.py
- locust/main.py
- locust/runners.py
- locust/static/locust.js
- locust/static/style.css
- locust/stats.py
- locust/templates/index.html
- locust/test/test_runners.py
- locust/test/test_stats.py
- locust/web.py
> Rename slave to worker (except changelog)

- docs/api.rst
- docs/increase-performance.rst
- docs/quickstart.rst
- docs/running-locust-distributed.rst
- docs/testing-other-systems.rst
- docs/writing-a-locustfile.rst
- examples/basic.py
- examples/browse_docs_sequence_test.py
- examples/browse_docs_test.py
- examples/custom_wait_function.py
- examples/custom_xmlrpc_client/xmlrpc_locustfile.py
- examples/dynamice_user_credentials.py
- examples/events.py
- examples/fast_http_locust.py
- examples/multiple_hosts.py
- examples/semaphore_wait.py
- locust/contrib/fasthttp.py
- locust/core.py
- locust/inspectlocust.py
- locust/main.py
- locust/runners.py
- locust/test/mock_locustfile.py
- locust/test/test_fasthttp.py
- locust/test/test_locust_class.py
- locust/test/test_main.py
- locust/test/test_runners.py
- locust/test/test_stats.py
- locust/test/test_taskratio.py
- locust/test/test_web.py
- locust/util/deprecation.py
This PR changes how tasks and TaskSets are declared on Locust classes. It's related to #1264 and an alternative approach to #1274. It sprung from multiple discussions with @cyberw around ways to simplify Locust for very simple cases.
All tests pass, but the documentation would still need updating before this could be merged.
The PR contains the following changes:
* Let users specify tasks directly under a Locust class, just as one would do it on a TaskSet class. These tasks will get the Locust instance as argument when executed.
Example:
```python
class User(Locust):
@task
def some_task(self):
pass
```
or:
```python
class User(Locust):
tasks = [SomeTaskSet, some_task]
```
or as a dict with weights:
```python
class User(Locust):
tasks = {SomeTaskSet:1, some_task:3}
```
* Removes …
> Allow tasks to be declared directly under Locust classes

- locust/core.py
- locust/runners.py
- locust/test/test_locust_class.py
- locust/test/test_runners.py
Decouples the runner code from the Locust user code by introducing Locust.start and Locust.stop methods.
The start() and stop() methods takes a gevent.pool.Group instance, and is responsible for spawning and killing a greenlet for the locust user. With this change the runner does no longer need to keep track of the state of the individual Locust instances, and the Locust instance does no longer need to be given a reference to the runner.
(This PR is based on the tasks-directly-under-locust-class branch, and shouldn't be merged until that PR is merged).
> Decouple Runner and Locust code by introducing Locust.start and Locust.stop methods

- locust/exception.py
- locust/rpc/zmqrpc.py
- locust/runners.py
- locust/test/test_runners.py
- locust/test/test_zmqrpc.py
With heartbeating enabled, I still noticed network issues (packet drop, invalid byte stream) in long-term running on k8s cluster (overlay network). 
And a straightforward fix is to reestablish the connection when any network issue is detected.
I've applied this fix in my locust tests for one week's running, and it works as expected.
> ensure the connection between master and slave in heartbeat

- docs/changelog.rst
- locust/core.py
- locust/event.py
- locust/runners.py
- locust/test/test_locust_class.py
- locust/test/test_runners.py
> Replace locust setup teardown with events

- docs/api.rst
- docs/changelog.rst
- docs/retrieving-stats.rst
- docs/running-locust-distributed.rst
- docs/running-locust-docker.rst
- docs/running-locust-in-step-load-mode.rst
- docs/running-locust-without-web-ui.rst
- docs/writing-a-locustfile.rst
- locust/argument_parser.py
- locust/core.py
- locust/main.py
- locust/stats.py
- locust/test/test_fasthttp.py
- locust/test/test_parser.py
This PR (for #1282) does the following
* Group related command line options together using Argument Groups from argparse, resulting in a much better `--help` message
* Removes deprecated `--no-reset-stats` options.
This PR is work in progress. Here's the current help output:
```
Usage: locust [OPTIONS] [LocustClass ...]
Common options:
-h, --help            show this help message and exit
-f LOCUSTFILE, --locustfile LOCUSTFILE
Python module file to import, e.g. '../other.py'. Default: locustfile
-H HOST, --host HOST  Host to load test in the following format: http://10.21.32.33
-c NUM_CLIENTS, --clients NUM_CLIENTS
Number of concurrent Locust users. Only used together with --headless
-r HATCH_RATE, --hatch-rate HATCH_RATE
The rate per second in which clients are spawned. Only used …
```
> Group related command line options together

- docs/changelog.rst
- locust/main.py
- locust/stats.py
- locust/templates/index.html
- locust/test/test_stats.py
- locust/test/test_web.py
- locust/web.py
This PR does:
* Add a column "User count" to the history CSV stats (should fix #1292)
* Makes the "Timestamp" column in history CSV the first column
* Remove the "Download response time history CSV" from Web UI since it has never worked, and fixing it is non-trivial (since we would either have to always store the whole stats history in memory, or always create a disk file somewhere, and I don't think we want to do either).
> Add User count to CSV history stats

- locust/core.py
New here, making a small change to some docs
> Fixed some spelling/grammar on docstrings in core.py

- docs/logging.rst
- locust/inspectlocust.py
- locust/log.py
- locust/main.py
- locust/runners.py
- locust/stats.py
- locust/test/mock_logging.py
- locust/test/test_log.py
- locust/test/testcases.py
PR for #1285. Does the following:
* We no longer wrap `sys.stdout` and `sys.stderr` (yay!). `print()` statements in locust scripts will no longer automatically go into the log. If someone wants to add entries to the log they can use the root logger instead (`logging.info(…)`), or any custom logger named `"locust.*"`.
* The "console_logger" logger has been removed. For printing stats to the console we now use a logger called `"locust.stats_logger"`. For printing output when using flags such as `--show-task-ratio` or `-l` we now use `print()` statements instead.
* We now set up an exception handler that logs any unhandled exception, for every greenlet we spawn (using Greenlet.link_exception) unless they already have their own exception handler (e.g. Locust User greenlets).
* Only allow …
> Improve how we do logging

- locust/main.py
For update in gevent 1.5.0(https://github.com/gevent/gevent/issues/1529), the usage of gevent.signal() should also be updated.
> Update main.py about gevent.signal()

- docs/writing-a-locustfile.rst
- locust/test/test_locust_class.py
- locust/test/test_runners.py
- locust/test/test_sequential_taskset.py
- locust/test/test_stats.py
- locust/test/test_wait_time.py
In documentation as well as test cases. Relates to #1328
> Import wait functions from locust instead of locust.wait_time

- locust/stats.py
When searching for an acceptable timestamp dictionary `t-CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW` is considered twice, because `t-CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW-0 == t-CURRENT_RESPONSE_TIME_PERCENTILE_WINDOW+0`
> Removed double consideration of same timestamp

- locust/runners.py
I need this for my global rps target to work (this change was part of the rejected #1241)
> Make all LocustRunners aware of their target_user_count, not just MasterLocustRunner

- locust/clients.py
- locust/contrib/fasthttp.py
- locust/test/test_client.py
- locust/test/test_fasthttp.py
> Allow multiple calls to response.failure() or response.success() within the same with block

- locust/argument_parser.py
- locust/env.py
- locust/main.py
- locust/test/mock_locustfile.py
- locust/test/test_main.py
- locust/test/util.py
As mentioned in #1339, web_host and web_port aren't actually being used. Fixed this and added a test for it.
Still not sure about saying "*" is the default web_host when it no longer is. I changed the docstring for this anyway but idk if "" still means "all interfaces"?
> Fix web options

- locust/argument_parser.py
> Give better error message when kubernetes env vars collide with locust's

- locust/argument_parser.py
- locust/env.py
- locust/main.py
- locust/test/test_web.py
- locust/web.py
- setup.py
- tox.ini
This adds support for serving the web UI over HTTPS. This shouldn't be the default behavior probably but if you have a cert I think you should be able to use it. Especially if basic auth is enabled.
This was first attempted and closed several years ago in locustio#282. I'm hoping that it can be readdressed today though. Most of the web is moving to HTTPS and I believe anything that ships a web server should also come with the ability to run it securely - especially with a package as widely used as Locust is.
Comments/feedback/suggestions welcome, happy to iterate and make this work however we can! I love the Locust project and am happy to help improve it.
> Add CLI params for TLS cert and key - serves over HTTPS

- .gitignore
- docs/changelog.rst
- docs/conf.py
- docs/configuration.rst
- docs/index.rst
- docs/quickstart.rst
- locust/argument_parser.py
- locust/main.py
* Automatically generate documentation for all available environment variables when documentation is built.
* Explicitly set environment variable names for the command line options.
* Rename env variables `LOCUST_MASTER`, `LOCUST_MASTER_PORT` in order to make it less likely that they collide with env vars automatically added by Kubernetes. Also change the name of `LOCUST_WORKER` and `LOCUST_MASTER_HOST` for consistency.
* Rename env variable `CSVFILEBASE` to `LOCUST_CSV`.
* Remove `--csv-base-name` command line option.¨
* Removed some redundant comments
> Environment variable configuration changes

- docs/configuration.rst
- docs/quickstart.rst
- locust/argument_parser.py
- locust/test/test_main.py
This PR adds a `--config` command line argument to locust.
Fixes #1334 
Includes tests and updates to docs.
The help text for the argument is a bit terse, I'd be happy to change that to something better.
> --config command line argument

- locust/test/test_locust_class.py
- locust/test/test_runners.py
- locust/user/task.py
This PR removes `args` and `kwargs` arguments from the internal `TaskSet.schedule_task` and `TaskSet.execute_task` methods.
Passing arguments to tasks was an old legacy feature that was never documented, and never used internally (except in tests). I think removing this feature in the name of KISS makes sense, since the feature aren't used internally, even though the methods are internal.
This will however be a breaking change for people who have looked at the Locust source and chosen to use this feature.
> Remove task arguments

- locust/main.py
> Try to increase open files limit and warn if it is still too low afterwards

- locust/main.py
- setup.py
... instead of its fork, now that there is a new release (I can trigger new releases later on as well). Relates to #1116
> Bump geventhttpclient and switch back to use its original repo 

- docs/running-locust-docker.rst
- locust/runners.py
- locust/test/test_runners.py
Just noticed this when I was browsing the documentation.
> Rename 3 remaining instances of slave to worker

- locust/templates/index.html
Some provide it as http://127.0.0.1:5000/
some provide it as 127.0.0.1:5000 which are wrong. Hence the example in the span tag
> The format for providing host can be confusing at times

- docs/changelog.rst
- docs/running-locust-without-web-ui.rst
- locust/env.py
- locust/event.py
- locust/main.py
- locust/runners.py
- locust/test/test_main.py
> Ability to control the Locust process' exit code

- locust/__init__.py
just add some commas 
this will avoid warnings like " 'events' is not declared in \_\_all\_\_ "
> update __init__ file

- docs/changelog.rst
A possessive belonging to an "it" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
> Remove Bad Apostrophe

- docs/writing-a-locustfile.rst
This PR adds some simple documentation to the "Writing a locustfile" page regarding the `init` event.
#1408
> Add simple documentation with use case for init event

- locust/stats.py
- locust/test/test_stats.py
- locust/web.py
> Use csv module to generate csv data

- docs/quickstart.rst
Quickstart documentation has one bit that's slightly confusing. Just a small edit.
> Quickstart documentation clarification.

- .dockerignore
- Dockerfile
- docs/changelog.rst
This PR makes Locust use the `python:3.8` docker image instead of `python:3.8-alpine` as the base image.
The reason for this is that it'll make it possible to `pip install ...` most PyPI packages out of the box, which should be a very common thing to do in project specific docker images. 
It comes with a ~900 MB cost in total image size, though I think the `python:3.8` image should be a very common base image to already have pulled, in which case there will effectively be no higher disk usage, and I think it makes sense to prioritize developer convenience and happiness over disk usage.
This is what the description at the [official docker python repo](https://hub.docker.com/_/python) says about the `python:3.8` image:
> This is the defacto image. If you are unsure about what your needs …
> Base Locust Docker image on non-alpine python image

- locust/static/chart.js
https://echarts.apache.org/en/option.html#yAxis.boundaryGap
Closes #1440
> Cut to only 5% free space on the top of the graphs

- locust/event.py
- locust/test/test_runners.py
An exception thrown during the handling of an event will stop the execution of other listeners.
Solves #1461
> Gracefully handle exceptions in event listeners

- locust/runners.py
Avoid issues like https://stackoverflow.com/questions/62769727/facing-error-address-already-in-use-while-running-locust
Instead of printing:
```
[2020-07-07 12:26:25,897] sonali-Latitude-3490/ERROR/stderr: Traceback (most recent call last):
[2020-07-07 12:26:25,897] sonali-Latitude-3490/ERROR/stderr: File "/home/sonali/.local/bin/locust", line 8, in <module>
[2020-07-07 12:26:25,897] sonali-Latitude-3490/ERROR/stderr: 
[2020-07-07 12:26:25,897] sonali-Latitude-3490/ERROR/stderr: sys.exit(main())
[2020-07-07 12:26:25,897] sonali-Latitude-3490/ERROR/stderr: 
[2020-07-07 12:26:25,897] sonali-Latitude-3490/ERROR/stderr: File "/home/sonali/.local/lib/python3.6/site-packages/locust/main.py", line 503, in main
[2020-07-07 12:26:25,898] sonali-Latitude-3490/ERROR/stderr: 
[2020-07-07 …
```
> Improve logging when locust master port is busy.

- locust/contrib/fasthttp.py
fix unhandled exception "ConnectionResetError: [Errno 104] Connection reset by peer"
> Handle connection reset error in fast http client

- locust/static/locust.js
Attempts to solve #1463, by fading into the dashboard screen.
> fade into the running screen before getting a response from the server

- locust/runners.py
I don't know what `Loadgen` means but AFAIK it's not a term used either in Locust or in the broader load testing field. I think it makes more sense without it? When I first saw this message I thought it was the name of a class or something 😅
> Remove "Loadgen" from CPU warning log messages

- locust/clients.py
- locust/test/test_wait_time.py
Resolves https://github.com/locustio/locust/issues/1487
I didn't replace it in parts related to stats as I'm not sure of the effect there. So I've replaced in these 3 parts where time is measured by subtracting a previous time from `time.time()`.
`FastHttpUser` is not affected by this problem in my testing. It uses a timer from the `timeit` package.
> Replace time.time() with time.monotonic()

- locust/main.py
Currently if `--web-host` option is not specified the message is:
`Starting web interface at http://:8089` which is an invalid URL and may confuse new users.
> Print valid URL when --web-host is not specified

- docs/writing-a-locustfile.rst
This is a left-behind us of `HttpLocust` that should be `HttpUser`
> Fix old HttpLocust reference in docs

- .gitignore
Since it looks like we're gonna [keep the messy formatting](https://github.com/locustio/locust/pull/1494) then I think we need to ignore `.editorconfig` 🙂
Also adding `__pycache__` as it shows these directories in a colour as if they would be committed by git (at least in Atom) and this is a little confusing:
> Add 2 things to .gitignore

- locust/runners.py
- locust/templates/index.html
- locust/test/test_runners.py
Resolves: https://github.com/locustio/locust/issues/1488
- Merge `stop_user_instances()` into `stop_users()`
- Allow `stop_rate` to be passed to `stop_users()`
- Negative or positive value for `stop_rate` does the same thing
- Copy same ramping behaviour from `spawn_users()`, it seems robust
- If no `stop_rate` passed to `stop_users()` then don't "ramp down", just stop all without sleeping
- Add one extra debug log message when running test is edited with new `user_count`/`hatch_rate` values
- Add test runner to ensure ramping down works
This is my first proper PR for this project so any and all feedback welcome 🙂
I have still yet to update any documentation...
> Allow ramping down of users

- locust/test/test_stats.py
This should have no real impact. It is just an array key that is "internal" to some test code.
> Fix typo of failure_percentage in test_stats.py

- locust/shape.py
- locust/static/style.css
- locust/templates/index.html
- Grey out input fields for starting and editing users and hatch rate when `LoadTestShape` is in use
- Add CSS style for above
- Remove unused `run_time = self.get_run_time()` from `shape.py`
> Grey out UI input fields when LoadTestShape is in use

- locust/argument_parser.py
- locust/main.py
- locust/stats.py
- locust/templates/index.html
- locust/test/test_parser.py
- locust/test/test_web.py
- locust/web.py
Adds another download link to the UI when --csv-full-history was specified
See: https://github.com/locustio/locust/issues/1468
Does not implement the suggested 'download-all'
> Download full history - see issue 1468

- docs/retrieving-stats.rst
- locust/env.py
- locust/main.py
- locust/stats.py
- locust/test/test_stats.py
- locust/test/test_web.py
- locust/web.py
The intent of is to reduce os calls and disk IO.
This code goes on top of my other PR https://github.com/locustio/locust/pull/1504, so submitting as draft.
> Keep csv files open

- docs/changelog.rst
- locust/argument_parser.py
- locust/main.py
The renamed events are still incompatible, but that should impact much fewer users.
Should we still call it 2.0? I guess we should.
ping @lhupfeldt
> Make hatch-rate parameter deprecated instead of killing it right away.

- examples/use_as_lib.py
- locust/main.py
- locust/stats.py
- locust/templates/index.html
- locust/templates/report.html
- locust/test/test_web.py
- locust/web.py
Export all statistics data to a `html` file, and you can **download** it to your computer.
As follows:
>  Add Feature: Download Report File

- README.md
- docs/api.rst
- docs/extending-locust.rst
- docs/running-locust-distributed.rst
- docs/running-locust-in-step-load-mode.rst
- docs/testing-other-systems.rst
- docs/what-is-locust.rst
- docs/writing-a-locustfile.rst
> Doc review changes

- locust/web.py
This was missing in https://github.com/locustio/locust/pull/1524, my bad
> Add missing parameter to render_template to grey out UI fields

- locust/stats.py
taken from https://github.com/taojy123/locust/commit/ce0e4d9f74884ce85fa6a3fce5de3b4ff257c112)
> fix #1531 (ValueError: StatsEntry.use_response_times_cache must be set to True)

- locust/runners.py
- locust/test/test_runners.py
Resolves https://github.com/locustio/locust/issues/1540
Reset state when stopping a `LoadTestShape` test and also add a test for this.
> Fix stopping and restarting of LoadTestShape test

- locust/runners.py
- locust/test/test_locust_class.py
- locust/test/test_runners.py
- locust/user/task.py
- locust/user/users.py
> Refactor and fix delayed user stopping in combination with on_stop

- locust/user/task.py
The parameters "args" and "kwargs" were removed in commit 82c2d6a68f946bdd303642dff6a89e0d5c2bf298. However they still show in the latest documentation https://docs.locust.io/en/latest/api.html?highlight=schedule_task#locust.TaskSet.schedule_task
> Update documentation for schedule_task parameters in TaskSet (task.py)

- locust/main.py
Will now print something like this to standard out:
```
[2020-09-17 09:39:33,411] 7131dd94fc3b/WARNING/locust.main: System open file limit '2048' is below recommended setting '10000'. It's not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
```
Since the expected setting isn't documented without this message it's
hard to know what the recommended value is.
> Add friendlier message about expected limit

- locust/runners.py
It's almost impossible to investigate issues like https://github.com/locustio/locust/issues/1535 and some of my previous issues without making custom local changes to add more logging, which is annoying and time consuming.
So here I'm adding some more debug log messages and add a function for updating the `state`, with a debug log message.
> Adding more debug logging for runners.py

- docs/writing-a-locustfile.rst
- locust/user/task.py
> Fixed documentation for tags to link properly.

- locust/runners.py
Resolves https://github.com/locustio/locust/issues/1577
> Don't log state change if it's the same

- docs/writing-a-locustfile.rst
- examples/browse_docs_sequence_test.py
- locust/user/sequential_taskset.py
- locust/user/task.py
Clarify documentation to indicate you can do multiple requests in a task without a SequentialTask.
Support task weights (repetitions) instead of silently ignoring them.
> SequentialTaskSet improvements

- docs/extending-locust.rst
- examples/extend_web_ui/extend.py
- examples/extend_web_ui/static/extend.js
- examples/extend_web_ui/templates/extend.html
- locust/event.py
- locust/main.py
- locust/static/chart.js
- locust/static/locust.js
- locust/static/style.css
- locust/templates/index.html
- locust/web.py
Addresses #1530. Includes the following additions and changes:
* `index.html` is extendable with blocks for tabs, panes, and scripts
* Args required to properly render `index.html` are retrievable via `web_ui.update_template_args()`
* Event for web UI's Reset Stats button to aid in custom data resetting
* Make some UI classes and functions more generic and more easily reusable for extended UI
> More easily extend web UI

- locust/env.py
- locust/main.py
- locust/runners.py
- locust/shape.py
Adresses #1557
The start time of a test with a shape should now be reset every time a new test is being run. Not from the time of locust init.
> Run time relative to start when using LoadTestShape

- locust/contrib/fasthttp.py
- locust/env.py
- locust/shape.py
- locust/test/test_locust_class.py
- locust/test/test_main.py
- locust/user/task.py
- locust/user/users.py
> Add more type hints

- README.md
- docs/increase-performance.rst
- docs/quickstart.rst
- docs/writing-a-locustfile.rst
- examples/add_command_line_argument.py
- examples/basic.py
- examples/dynamice_user_credentials.py
- examples/events.py
- examples/fast_http_locust.py
- examples/locustfile.py
- examples/multiple_hosts.py
- examples/use_as_lib.py
- locust/test/test_locust_class.py
- locust/test/test_runners.py
- locust/test/test_sequential_taskset.py
- locust/test/test_wait_time.py
- locust/user/users.py
Make wait_time = constant(0) the default instead of forcing our users to specify it on every user class. 
This makes a big difference in readability of small User classes and reduces the cognitive overhead for locust beginners. Fixes #1308
> Make zero wait time the default

- docs/quickstart.rst
- locust/argument_parser.py
- locust/input_events.py
- locust/main.py
- locust/test/test_main.py
- setup.py
- tox.ini
w = increase by 1
W = increase by 10
s = stop 1
S = stop 10
fixes #1600
> Add key commands for increasing and stopping users 

- locust/input_events.py
- locust/test/test_main.py
Raise and catch an exception when failing to get terminal attributes.
> Fix 100% cpu usage when running in docker/non-tty terminal

- locust/argument_parser.py
- locust/html.py
- locust/main.py
- locust/test/test_main.py
- locust/web.py
This is a fork of @vsapronov's PR https://github.com/locustio/locust/pull/1611, with the addition of a test.
> Added --html option to save HTML report

- locust/runners.py
- locust/test/test_runners.py
> Fix bug causing test_stop event to be fired twice in master node

- examples/manual_stats_reporting.py
This PR adds an example with a `manual_report()` decorator/context manager that can be used to easily measure the time of functions/code blocks and manually report them as stats entries to the Locust statistics.
I wrote up the `manual_report()` functionality as an example for a user in the Locust Slack, and I think it turned out pretty.
We could also consider actually making `manual_report` part of Locust's API. For example under`locust.contrib.report.manual_report`. Though I'm not sure it's useful enough to warrant including it with locust itself?
**Usage example as a context manager:**
```python
with manual_report("stats entry name"):
```
**Usage as a decorator:**
```python
@task
@manual_report
def my_task(self):
```
Even if we don't want to add it udner …
> Add example that manually adds stats entries

- locust/input_events.py
fixes #1654 
The windows keypoller wasn't checking if the stdin was a tty. Causing errors when running locust in non-tty windows environments.
> Check if running from a tty on windows

- locust/web.py
for web /swarm endpoint moved extracting user_count and spawn_rate after checking if shape_class is used. if shape class is used these values are ignored
Fixes #1670
> /swarm adjusted for tests with shape class

- locust/stats.py
- locust/test/test_stats.py
- locust/web.py
> Feature stats exceptions csv

- locust/static/chart.js
- locust/static/locust.js
- locust/stats.py
- locust/templates/index.html
- locust/templates/report.html
- locust/templates/stats_data.html
- locust/web.py
This PR improves the charts of the index and the report page with the following changes:
- Prevent to continue reporting stats to the history of stats when the runner is stopped
- Usage of shared template to build stats_history data to reload to charts data in the index.html and report.html templates
- Fix Report Charts tooltips user count values
Fixes #1677
> Feature chart sync

- locust/html.py
- locust/templates/stats_data.html
- locust/web.py
> Improve stats data sharing from python to js

- locust/html.py
- locust/test/testcases.py
Restore the custom html.py render_template function to fix tests
> Fix issues with render_template

- locust/main.py
- locust/runners.py
- locust/test/test_main.py
Resolves https://github.com/locustio/locust/issues/1653
> Shutdown workers when using LoadTestShape and headless mode

- .github/workflows/tests.yml
- locust/main.py
- locust/test/test_main.py
This PR also fixes a couple of broken tests.
Releases to PyPI are *not* handled yet, but that can be a different PR I think.
> Use Github Actions for CI

- .github/workflows/tests.yml
* Add step to CI Tests for verifying that docker build works.
* Create PyPI releases through Github Actions when tags are pushed
> Verify docker build & create PyPI releases through Github Actions when tags are pushed

- locust/static/locust.js
This PR solves the regression issue #1690 
Combine the dynamic stats values with the new persistence chart stats
> fix stats values for chart tooltips

- examples/custom_shape/double_wave.py
Currently it might not be directly clear where the peaks are for double wave load shape class. Adding for clarification.
> updated double wave load shape docs to reflect peak times

- locust/event.py
When I add an event listener, my IDE complains about the type of the decorated function. This will fix that by making sure that the annotation of the attributes of Events are an instance of EventHook (and not the class EventHook).
> fix type hinting on Events

- locust/runners.py
- locust/test/test_runners.py
This PR fixes #1707 by not subtracting missing workers from the active workers list (which excludes missing workers already).
Also adds another log message when workers are coming back (including currently active users - which required an event data extension).
The existing test `test_runners::test_last_worker_missing_stops_test` was also checking for the wrong state (missed to check for "stopping" in addition to "stopped", since the created clients cannot react to a stop event in the test.
> Fix automatic distributed test shutdown

- docs/generating-custom-load-shape.rst
- examples/custom_shape/wait_user_count.py
- locust/env.py
- locust/shape.py
- locust/test/test_runners.py
> make user count available to LoadTestShape

- locust/runners.py
Workaround for #1726
This should change it from throwing an exception (and thus failing to stop), to instead logging an error message and then moving on (havent been able to test it 100% though). May give us some more info for a proper fix as well.
[2021-03-11 12:54:24,150] lafp-mac-JG5J.int.svenskaspel.se/INFO/locust.main: Shutting down (exit code 0), bye.
[2021-03-11 12:54:24,150] lafp-mac-JG5J.int.svenskaspel.se/INFO/locust.main: Cleaning up runner...
[2021-03-11 12:54:24,150] lafp-mac-JG5J.int.svenskaspel.se/ERROR/locust.runners: Found a user that didnt have proper args <Greenlet "Greenlet-0" at 0x112c863b0: run_user(<player_settings.WebUser object at 0x112b1f650>)>
> Ensure runner.quit finishes even when users are broken

- .git-blame-ignore-revs
- docs/api.rst
- docs/changelog.rst
- docs/extending-locust.rst
- docs/testing-other-systems.rst
- examples/custom_xmlrpc_client/xmlrpc_locustfile.py
- examples/events.py
- examples/extend_web_ui/extend.py
- examples/manual_stats_reporting.py
- locust/clients.py
- locust/contrib/fasthttp.py
- locust/event.py
- locust/runners.py
- locust/test/test_fasthttp.py
- locust/test/test_http.py
- locust/test/test_locust_class.py
- locust/test/test_runners.py
- locust/test/util.py
- locust/user/users.py
- tox.ini
Add a single event thats triggered both on request succes/failure #1724
This new event can contain metadata (called context) which can be specified when performing the request.
> Updated request event with context 

- examples/custom_xmlrpc_client/xmlrpc_locustfile.py
- examples/grpc/locustfile.py
- locust/clients.py
- locust/contrib/fasthttp.py
- locust/shape.py
- locust/test/test_runners.py
- locust/test/test_wait_time.py
... instead of a mix of time.monotonic(), which sometimes has less precision, and timeit (used in FastHttpUser), which has undesirable effects like disabling GC.
Also, in FastHttpUser, dont round response times to millisecond for no reason.
Note: On Linux/mac .perf_counter() calls .monotonic() in the end, so there is no difference there
> Measure elapsed time using time.perf_counter() 

- locust/runners.py
Old update was causing issues when using a custom user that manually triggered request_success/request_failure. Resulting in some sneaky errors. This should keep old users from breaking while still allowing for use of the new request event.
> Register stats from request_success and request_failure

- locust/runners.py
added STATE_INIT to condition in check_stopped condition for clients - it looks like there's possibility that master is not in STATE_INIT anymore, but some client didn't have enough time to change the state
> modified check_stopped condition

- locust/html.py
- locust/test/test_web.py
This PR fixes the following issue:
```
[2021-06-09 20:36:13,702] master1/CRITICAL/locust.runners: Unhandled exception in greenlet: <Greenlet at 0x7ff41a2846a0: <bound method MasterRunner.client_listener of <locust.runners.MasterRunner object at 0x7ff3ea9d4b80>>>
Traceback (most recent call last):
File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
File "/home/adminuser/.venv/lib/python3.8/site-packages/locust/runners.py", line 842, in client_listener
self.log_exception(msg.node_id, msg.data["msg"], msg.data["traceback"])
File "/home/adminuser/.venv/lib/python3.8/site-packages/locust/runners.py", line 422, in log_exception
row["nodes"].add(node_id)
AttributeError: 'str' object has no attribute 'add'
```
If a user generated a html report during a load test run, …
> Ensure that the exception dictionaries are not mutated when generating a html report

- docs/api.rst
- docs/running-locust-distributed.rst
- examples/custom_messages.py
- locust/runners.py
- locust/test/test_runners.py
This pull fixes #1780 and #1506. 
Added two methods, `register_message` and `send_message` to the two `DistributedRunner` classes.
`register_message` takes a custom message type and a callback function to call when the specified message is received. The callback's parameters are `environment` (obviously the runner's environment) and `msg`, which is the message itself. 
`send_message` takes a custom message type and optional data to send with the message, allowing a user to easily send their own custom messages.
Updated tests/documentation where necessary, added an example implementation to the examples directory (`examples\custom_messages.py`).
> Allow cross process communication using custom messages

- locust/test/testcases.py
- locust/web.py
- setup.py
- tox.ini
I noticed in issue #1759 that the flask version was pinned to the 1.x branch to fix compatibility issues. This PR introduces the necessary changes to bump Flask and werkzeug to version 2.x .
> Upgrade to flask 2

- docs/extending-locust.rst
- docs/writing-a-locustfile.rst
- locust/event.py
- locust/runners.py
- locust/test/test_runners.py
PR to fix #1776 
Added `test_start` and `test_stop` events to the base `Runner` class' `start()` and `stop()` method, respectively
Added/updated relevant tests and documentation.
> Fire test_start and test_stop events on worker nodes

- locust/runners.py
- locust/test/test_runners.py
`user_classes_count` is already part of the stats payload so having it in the heartbeat payload is redundant and makes the payload larger.
TODO:
> Remove `user_classes_count` from heartbeat payload

- locust/test/test_dispatch.py
- locust/test/test_runners.py
Before:
```
================================================================================================================================================== slowest durations ===================================================================================================================================================
76.82s call     locust/test/test_runners.py::TestMasterWorkerRunners::test_distributed_shape_with_stop_timeout
30.28s call     locust/test/test_runners.py::TestMasterWorkerRunners::test_distributed_shape_statuses_transition
26.41s call     locust/test/test_dispatch.py::TestRampUpThenDownThenUp::test_ramp_up_then_down_then_up
20.31s call     locust/test/test_runners.py::TestMasterWorkerRunners::test_swarm_endpoint_is_non_blocking
19.25s call …
```
> Speed up tests

- locust/runners.py
- locust/test/test_runners.py
Also add test case for version checking. Helps a little with #1827.
> Allow workers to bypass version check by sending -1 as version

- docs/configuration.rst
- docs/extending-locust.rst
- examples/add_command_line_argument.py
- locust/argument_parser.py
- locust/runners.py
- locust/templates/index.html
- locust/test/test_runners.py
- locust/test/test_web.py
- locust/web.py
This is WIP. I'm not sure showing all custom arguments in the UI is the best solution (and it would also be nice to be able to show some of the default ones). What do you think @TWoeste
I tried to make that "advanced" tab thingy but it turned out to be too much work :)
> Show custom arguments in web ui and forward them to worker

- locust/argument_parser.py
- locust/env.py
- locust/main.py
- locust/test/test_env.py
Issue: https://github.com/locustio/locust/issues/1838
> Add equal weights flag

- locust/stats.py
- locust/templates/report.html
- locust/templates/stats_data.html
Server-side stats history time sourcing changed from server time(time zone dependent) to UTC, aligning it with other server-side time values sourced from `time.time()`. This enables the same frame of reference for all clients by knowing it is UTC. Localization is now performed client-side on server-rendered dates and times.  
Localization of the `report.html` start and end datetimes intentionally formats the value according to the client's default locale to keep with the localization theme of this change.
The date strings are manually parsed instead of using `Date.parse()` as recommended by MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parsed
`"It is not recommended to use Date.parse as until ES5, parsing of strings was entirely implementation …
> Use UTC time for server stats history, localize times on the client

- locust/clients.py
Changes something like
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='asdf.se', port=345): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10f1d0d60>: Failed to establish a new connection: [Errno 61] Connection refused'))"))
Into:
ConnectionRefusedError(61, 'Connection refused')
> HttpUser: Unpack known exceptions

- locust/static/locust.js
- locust/stats.py
- locust/templates/stats_data.html
- locust/test/test_stats.py
- locust/web.py
Stat history would be charted by the client as a stream of consciousness
from the runners until they are stopped.
The client will no longer show unquantified stats (represented by the
number of requests).
Issue: #1852
State checking logic on the client has also been flattened to simplify the flow.
Considerations:
- By only showing stats that contain request, there might be an appearance of unresponsiveness until requests are made because the chart will no longer be "ticking" without them.
- The aggregated `total` stats are used to determine the number of requests, this is to allow a transition from `ready` state to `running` state to be displayed.
- The times on the x-axis of charts diverge between a page that has been running for a while and a page refresh, this is because the client …
> fix(charts): prevent displaying stats before requests are made

- examples/multiple_hosts.py
Sync `multiple_hosts.py` creation of `HttpSession` with the new constructor signature.
Fixes: #1775
> fix(examples): fix multiple_hosts.py example

- locust/env.py
- locust/test/test_env.py
> Handle user classes with weight = 0

- docs/index.rst
- docs/testing-other-systems.rst
- docs/testing-requests-based SDK's.rst
- docs/writing-a-locustfile.rst
- examples/sdk_session_patching/session_patch_locustfile.py
- locust/clients.py
- locust/test/test_stats.py
- Add an alternative way to group requests together, do deal with situations where passing in a name parameter is not possible
- Add examples using the alternative grouping approaches.
- Added an example of session patching when working with SDK's
> Alternative grouping

- examples/extend_web_ui/static/custom-stats-table.css
- examples/extend_web_ui/static/extend.css
- examples/extend_web_ui/templates/extend.html
- locust/templates/index.html
There is no (SSR) way to inject custom elements in the `head` when extending the `index.html` jinja2 template
Add a new jinja2 block `extend_head` to the `index.html` template to improve customizability. For example:
```jinja2
{% extends "index.html" %}
{% block extended_head %}
<link rel="stylesheet" type="text/css" href="./extend/static/extend.css?v={{ version }}" media="screen">
{% endblock extended_head %}
```
This is how the `extend_web_ui` example looks like with the new table styling:
> Ability to inject custom html elements in the `head` element

- locust/stats.py
- locust/templates/index.html
- locust/test/test_stats.py
The docstring for _stats_history_data_rows says it should be outputting `*current* stats` (emphasis not added by me). In the original commit from December 3rd, 2019, it was properly using the `get_current_response_time_percentile` function.
On August 18th, 2020, the code was all reformatted and it looks like a regression was accidentally introduced when they switched over to using `get_response_time_percentile` instead.
This PR simply fixes that regression, switching back to using `get_current_response_time_percentile`.
The bug is easiest to observe if you have a spikey/bursty test shape. During bursts, latency increases. During quieter times, latency goes back down. This is properly reflected in the Locust Web UI's graph tab, but the full history CSV file doesn't show that - instead …
> Fix Regression in Full History CSV Percentiles

- examples/add_command_line_argument.py
- locust/argument_parser.py
- locust/test/test_parser.py
- locust/web.py
> Ability to hide extra args from web ui

- locust/argument_parser.py
- locust/runners.py
- locust/test/test_runners.py
- tox.ini
- Adding a new argument to enable automatic rebalancing for new workers (after ramp up completed)
- Log message added when rebalancing is triggered
To be checked how to test such code change.
cc @cyberw  @mboutet
> #1884 User distribution should happen when new workers comes in

- locust/runners.py
- locust/test/test_runners.py
> Ensure target_user_count is set before ramping-up or down

- locust/argument_parser.py
- locust/main.py
- locust/test/test_main.py
This is very useful in CI, where you dont want to wait forever if your workers fail to connect.
> Add --expect-workers-max-wait parameter

- docs/writing-a-locustfile.rst
Changed "executition" to "execution".
> Fixed typo in writing-a-locustfile.rst

- docs/changelog.rst
- docs/testing-requests-based SDK's.rst
- docs/writing-a-locustfile.rst
Hello.
Some misspellings I found while reading the documentation.
> fix misspellings in doc (mostly "it's")

- docs/api.rst
- locust/argument_parser.py
- locust/contrib/fasthttp.py
- locust/env.py
- locust/stats.py
- locust/user/users.py
Do it in constructor/instance level, where they belong instead.
The only benefit to having them on class level was so that they got documented properly, but it works as long as they are definied in __init__ as well.
While this shouldnt be a breaking change for any "normal" usage of Locust, I think we need to do some testing to ensure that we dont need to bump major version.
Added some type hints as well.
> Stop declaring "fake" class level variables in Environment, User and StatsEntry

- locust/clients.py
- locust/contrib/fasthttp.py
- locust/test/test_fasthttp.py
- locust/test/test_http.py
For when `catch_response=True` is set, but someone forgot to do a with-block...
> Throw exception when calling response.success()/.failure() if with-block has not been entered

- locust/runners.py
- locust/test/test_runners.py
I have the use case of two clients, each defining `host` as a class attribute. When running with `--headless`, it works fine, but when running with the UI, I kept getting errors like
```
[2021-12-09 14:32:00,340] localhost.localdomain/ERROR/locust.user.task: Invalid URL '/index.html': No schema supplied. Perhaps you meant http:///index.html?                    
Traceback (most recent call last):                                                                                                                                                            
File "/home/chaen/miniconda3/envs/diracprod/lib/python3.9/site-packages/locust/user/task.py", line 296, in run                                                                 
self.execute_next_task()
File …
```
> Fix running the web UI with class defined hosts

- locust/runners.py
> Ensure heartbeat_worker doesnt try to re-establish connection to workers when quit has been called

- locust/main.py
- locust/test/test_log.py
- locust/test/test_main.py
Make "Running teardowns..." and "cleaning up runner..." log messages debug instead of info. Shorten "Shutting down ..." message.
> Clean up some logging messages

- locust/runners.py
So that a worker can know how many other processes will be running. This is kind of ugly and arbitrary, but I dont have time to do a proper re-think of argument passing.
> WorkerRunner: read --expect-workers from job parameters

- docs/api.rst
- docs/writing-a-locustfile.rst
- locust/argument_parser.py
- locust/dispatch.py
- locust/html.py
- locust/main.py
- locust/static/tasks.js
- locust/templates/index.html
- locust/test/test_dispatch.py
- locust/test/test_main.py
- locust/test/test_runners.py
- locust/test/test_stats.py
- locust/test/test_taskratio.py
- locust/user/inspectuser.py
- locust/user/users.py
- locust/web.py
Issue #1939
Here is the overall working option, but noticed a problem with the display 'Ratio per User class' and 'Total ratio' on web UI.
I'm going to redo the logic a little bit, get_task_ratio_dict it will recalculate the ratio based on the number of users at the moment. I'll make it a separate commit in same branch. Maybe there are other ideas?
> fixed_count: ability to spawn a specific number of users (as opposed to just using weights)

- locust/env.py
- locust/main.py
- locust/runners.py
- locust/test/test_main.py
This required moving the call to filter_tasks_by_tags from Environment init to Runner.start/start_worker. Fixes #1882
> Pass tags and exclude-tags to workers. 

- docs/running-cloud-integration.rst
A small PR to fix currently not working/visible hyperlinks under the [More information](http://docs.locust.io/en/stable/running-cloud-integration.html#more-information)-section
I'm not familiar with how `:ref:` statements work in `.rst` files, so if they are important for these links (I don't think so), please feel free to improve on my PR.
> Repair broken hyperlinks in documentation

- docs/running-cloud-integration.rst
Hopefully fixes #1978
I'm sorry this seems to be ending up in a "trial-and-error". I just don't know how to quickly verify changes to .rst files locally.
> Fix docs with underscore postfix for hyperlink?

- examples/grpc/locustfile.py
Example Grpc client not reporting stats when Locust is running as a library.
Fixed by firing requests through Environment.events.request.fire instead of locust.events.request.fire
Related Issue: https://github.com/locustio/locust/issues/1969
> Fire requests through Environment.events

- locust/env.py
- locust/test/test_env.py
Hardening for issue https://github.com/locustio/locust/issues/1981, make it more clear if the user made a mistake.
Signed-off-by: Chenyang Yan <memory.yancy@gmail.com>
> hardening Environment.shape_class for distinct usage

- locust/runners.py
- locust/test/test_runners.py
This reverts #1935 ("fix master runner not close rpc server"), because it caused real issues for regular runs (#1971) (maybe as-a-library worked, idk). 
This will reintroduce the problem regarding repeated as-a-library-runs @lizhaode was trying to fix in that PR, but we cant have regular runs throwing exceptions...
(this also reverts my attempted fix in #1972)
> Fix "socket operation on non-socket" at shutdown, by reverting #1935

- locust/argument_parser.py
- locust/main.py
- locust/web.py
If locust is started by `--headful` argument(web mode), `main_greenlet.join()` will serve forever. `get_html_report` will be inaccessable.
If running locust will be CTRL+C, `get_html_report` will not be received by catching the exception.
In order to keep simple, `get_html_report` is dealt with `shutdown()` according to `--html` argument value.
Signed-off-by: Chenyang Yan <memory.yancy@gmail.com>
Edit: Fixes #1944
> fix --html report in web mode

- docs/running-in-debugger.rst
- examples/debugging_advanced.py
- locust/debug.py
- tox.ini
... without messing up its Environment instance. Add debugging_advanced.py that shows the use, and a test for it in tox
> Allow repeated runs of run_single_user 

- locust/static/tasks.js
In order to allow the rendering of Tasks on downloaded reports, it need to handle the case get /tasks is not fulfilled.
cc @cyberw @EzR1d3r
> #1994 Fixing to fallback in case of local execution

- MANIFEST.in
- locust/py.typed
- locust/user/task.py
Partially resolves #2000, not all parts of the public API are fully typed.
This PR adds the `py.typed` file to the package distribution and adds type hints to `@task`, `@tag` and a couple other miscellaneous places.
> Mark package as being typed and add some missing type hints

- examples/test_data_management.py
- locust/event.py
- locust/runners.py
- locust/test/test_runners.py
Adding test_stopping event - fired before stopping users.
It resolves #2031
> Add test_stopping event

- .gitignore
- locust/clients.py
- locust/contrib/fasthttp.py
- locust/debug.py
- locust/dispatch.py
- locust/env.py
- locust/input_events.py
- locust/runners.py
- locust/shape.py
- locust/stats.py
- locust/test/__init__.py
- locust/test/mock_logging.py
- locust/test/test_dispatch.py
- locust/test/test_log.py
- locust/test/test_runners.py
- locust/user/task.py
- locust/user/users.py
- locust/util/deprecation.py
- locust/web.py
- setup.cfg
- setup.py
- tox.ini
tried to update locust to 2.8 in a project that uses mypy for static type checking and ran into problems.
noticed that `locust/py.typed` had been added (TIL). i've tried to cleanup the typing in locust by running mypy with default settings and fixing the errors.
```
➜ mypy --ignore-missing-imports locust/ --exclude locust/test
locust/clients.py:4: error: Library stubs not installed for "requests" (or incompatible with Python 3.8)
locust/clients.py:4: note: Hint: "python3 -m pip install types-requests"
locust/clients.py:4: note: (or run "mypy --install-types" to install all missing stub packages)
locust/clients.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
locust/clients.py:6: error: Library stubs not installed for "requests.auth" (or incompatible …
```
> fixing mypy errors with loosest rules

- docs/increase-performance.rst
- docs/writing-a-locustfile.rst
- locust/clients.py
- locust/contrib/fasthttp.py
- locust/test/test_fasthttp.py
- locust/test/test_users.py
- locust/test/testcases.py
- locust/user/users.py
This PR adds support for sharing connection pools between users. It is done by exposing lower level pool (`urllib3.PoolManager` for `HttpUser`, `geventhttpclient.client.HTTPClientPool` for `FastHttpUser`).
Example usage:
```python
from geventhttpclient.client import HTTPClientPool
from locust import FastHttpUser, HttpUser
from urllib3 import PoolManager
class UserA(HttpUser):
pool_manager = PoolManager(maxsize=10, block=True)
class UserB(FastHttpUser):
client_pool = HTTPClientPool(concurrency=10)
```
Fixes #1925.
> Support sharing connection pools between users

- .github/workflows/tests.yml
- tox.ini
In this model, linters are only run once.
> Move lint tests to their own tox environments

- locust/runners.py
- locust/test/test_runners.py
Fixes #1986
I tested with the steps indicated in https://github.com/locustio/locust/issues/1986#issue-1116128138 and only a single `'test_start' triggered 1 times.` is printed.
TODO:
> Ensure `test_start` is run to completion on worker

- .github/workflows/tests.yml
- Dockerfile
- locust/test/test_runners.py
- pyproject.toml
- setup.cfg
- setup.py
- tox.ini
i mentioned in a previous PR #2040 that there was problems adding locust as a git dependency; pip or pip-tools got confused that there was a `pyproject.toml`, but no `build-system` section available. all it contained was settings for `black`.
there have been other projects having the [same problem](https://snarky.ca/what-the-heck-is-pyproject-toml/).
the underlying problem seems to have been fixed now, so it is indeed possible to have locust as a git dependency (which I realized after implementing this...). but there are probably other benefits of moderizing the build setup to be PEP517 and PEP518 compatible.
since most stuff already was present in `setup.cfg`, it was quite an easy transition to move away from `setup.py`, however editable installs is not yet supported by `pyproject.toml` …
> modernized build

- locust/stats.py
- locust/test/test_stats.py
I'm using the console statistics tables to get a quick summary of how a test went, and one thing that has annoyed me a bit, is that `print_stats`, `print_percentile_stats` and `print_error_report` ascii tables all have different "style".
Especially `print_stats`, where `method` and `name` is concatenated to one string, resulting in, e.g. `GET` and `POST` entries are misaligned.
Off the 3 styles, I liked the `print_percentile_stats` most, so fixed the other 2 to have the same style.
Comparision with before and after;
`print_stats`:
```plain
Name                                                                              # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
----------------------------------------------------------------------------------------------- …
```
> uniform style of stats/report ascii tables

- locust/main.py
Resolves https://github.com/locustio/locust/issues/2075
The problem is that if `--headless` is used with `LoadTestShape` then the  `stats_csv_writer` greenlet is never spawned. By moving the `gevent.spawn(stats_csv_writer.stats_writer)` part up a few lines I think it solves the problem? Let's wait for the tests 🙏
> Move CSV stats printer gevent spawn up a few lines

- locust/contrib/fasthttp.py
- locust/test/test_fasthttp.py
- locust/test/test_runners.py
- locust/test/testcases.py
Sorry for the long "intro", which might seem irrelevant at first... but bear with me :)
In "my" project I had a case where I wanted to create a group of [async] requests, by running them in their own `greenlet`.
Normally it uses the `requests` client via `HttpUser`, but the way `requests` is using the `ConnectionPool` from `urllib3` is not thread-safe[0], which caused the requests to run more or less sequential instead.
This lead me to using a `FastHttpSession` for each async request, which worked great for that part. But instead ran into some typing issues, e.g.:
```python
class FastResponse(CompatResponse):
headers = None
...
```
Since `geventhttpclient` isn't typed, this causes `mypy` to think that `headers` is always `None`, causing it to get type `Never`, making it hard to actually …
> FastHttpUser improvements (including a rename of parameter "url" to "path")

- locust/stats.py
- locust/test/test_stats.py
the width of the `print_stats` table was increased in a previous PR, which resulted in line wraps in terminal sizes that previously didn't have it (see discussion in #2084).
this PR tries to solve that. in the case of a big terminal window causing  `STATS_NAME_WIDTH` to be at max 80 characters, the table is now 1 character less wide than the original implementation (before #2084), 159 columns vs 158 columns.
this is an comparision of the output of the tables with this PR and the original implementation with a 119 column wide terminal:
the original implementation would allow a request name of maximum 34 characters in the `DELETE` request type case, and 37 characters in the `GET` request type case.
with the new implementation, the maximum request name length, with 119 columns, would always …
> print_stats table width fix for #2084

- locust/dispatch.py
- locust/test/test_dispatch.py
Fixes https://github.com/locustio/locust/issues/2091
* Resets the user worker count before rebalancing since `_user_gen` compares the expected number of fixed count users with the users in `self._users_on_workers`
* Sets `self._try_dispatch_fixed = True` to include fixed users in the rebalance
* Extends `TestAddWorker` and `TestRemoveWorker` to add a test for fixed count (which both fail without this commit) - these just copy `test_remove_worker_during_ramp_up` and `test_add_worker_during_ramp_up` with a fixed user
> dispatch: rebalance users with a fixed count

- locust/runners.py
- locust/test/test_runners.py
Fix for issue [2036](https://github.com/locustio/locust/issues/2036)
> Fix multiple resetting connection after RPCError

- locust/runners.py
fix: client_listener will raise an KeyError error when received a client_stopped message from an unknown worker.
> Stop client_listener from raising a KeyError when receiving a client_stopped message from unknown worker

- locust/dispatch.py
- locust/env.py
- locust/runners.py
- locust/stats.py
- locust/user/inspectuser.py
- locust/user/task.py
- locust/web.py
- setup.cfg
when doing some "integration" work with `RequestStats`, i noticed that there was a lot of stuff that was missing types and had inferred `Any`.
so this PR started out with the goal to add typing to `locust.stats` which took me down a rabbit hole of also adding types in `locust.env`, `locust.web`, `locust.runners` and `locust.user`.
i had to get creative in some places, which added a bit more code than just the types, mostly due to how many variables has an initial value of `None`.
also, maybe a bit unnecessary... but `StatsEntry` had `serialize` and `unserialize`, while `StatsError` for the same thing had `to_dict` and `from_dict`, so changed it so they have the same names.
> additional typing improvements

- Dockerfile
- locust/runners.py
- locust/test/test_runners.py
adding test for worker connection.
Details is issue: https://github.com/locustio/locust/issues/2044
> Add ack for worker connection

- locust/runners.py
- locust/test/test_runners.py
As per the issue https://github.com/locustio/locust/issues/2111 when running locust in distributed mode with more than 1 worker when the job is stopped the state is kept as STOPPING. Doing some investigation I realised after it removes a client from the list it gets back as a `ready` one, thus when the `check_stopped()` is called it checks the state for all clients, as the operation is fast, before checking the second client the first one is already `ready` and pass the `update_state(STATE_STOPPED)`
This PR intends to fix this bug hence to fix the continuously RPS in the graph even with the test "stopped" (issue with the graph shown bellow).
> fix: stopping state when running more than one worker node.

- locust/contrib/fasthttp.py
- locust/test/test_fasthttp.py
As per https://github.com/locustio/locust/issues/2066, currently there's no option for setting up certificates when using `FastHttpUser`. This PR intends to add a new `ssl_context_factory` param to enabling this functionality by defining a custom `Callable` returning a SSLContext when implementing the user.
As the callable will be called within the class context if it is defined outside the `ApiLocust` class we need to fake an arg there. The two example on how implementing can be found below.
**Option 1**
```python
import gevent
from locust import task
from locust.contrib.fasthttp import FastHttpUser
def my_custom_context(*args):
context = gevent.ssl.create_default_context()
context.check_hostname = True
context.verify_mode = gevent.ssl.CERT_REQUIRED …
```
> add support for custom SSLContext when using FastHttpUser

- README.md
Link was killed in:
https://github.com/SvenskaSpel/locust-plugins/commit/91e431e2c5c4da39b385e8f717809c280c1577ad
And the new link was moved again in:
https://github.com/SvenskaSpel/locust-plugins/commit/9426d6d1ca491260e5fe16807f3991d6f0711b13
As of today, the other two links on this line still appear to be correct.
> Update the link for reporting data to a database

- locust/exception.py
- locust/rpc/zmqrpc.py
- locust/runners.py
- locust/test/test_runners.py
- locust/test/test_zmqrpc.py
When using Boomer as a worker runner, I encountered some occasional errors on the master when receiving reports from the workers. In that situation, current Locust would break itself by attempting to reset the entire RPC server. Firstly, various issues prevented that from completing successfully. This broke the entire test instead of just fixing the one worker. Secondly, that isn't always necessary for the master to do. In most cases, subsequent reports from the workers are fine. In some other cases, the worker with the bad message resetting its connection to the master can resolve it. This will now reserve the master resetting its server to times when the master gets an error attempting to send to a worker, or if there's any other unexpected `RPCError` that gets thrown.
> More robust handling of ZMQ/RPC errors

- locust/html.py
- locust/templates/report.html
This is a quick fix for issue #2126, possibly not the most elegant solution.
> Escape user supplied data in html report (#2126)

- locust/stats.py
MD5 is old, insecure, and can create problems for people using this package when they are trying to pass some compliance requirements (for example, FIPS).
> Replace the MD5 usage by SHA256

- locust/web.py
when the stacktrace of exceptions contains some html, then the rendering (and possibly more) breaks.
In my case it was some method with parameter value `'<!DOCTYPE'`. Then the stacktrace stops afterwards
> Fix escaping for exceptions in normal web ui (related to #2126)

- locust/templates/report.html
This PR implements the following feature request #2132.
It enables sorting the statistic tables by clicking on the respective table headers.
To make the headers clickable, the class `sortable` needs to be applied. This makes it possible to ex-/include columns from being sort-able.
I only excluded the error messages as well as the stacktraces from being sort-able from now on.
Changes are welcome.
> Test Report: Implement table sorting

- locust/runners.py
The connection timeout and number of attempts are hardcoded (60 attempts with an interval of 5 seconds each), so a complete failure of the worker to connect to master will take very long.
These log lines will allow to troubleshoot issues with the connection to master.
> Log an error for every failed attempt to connect to master

- docs/configuration.rst
- docs/developing-locust.rst
- docs/further-reading.rst
- docs/increase-performance.rst
- docs/installation.rst
- docs/quickstart.rst
- docs/running-distributed.rst
- docs/running-in-debugger.rst
- docs/running-in-docker.rst
- docs/running-without-web-ui.rst
- docs/testing-other-systems.rst
- docs/testing-requests-based SDK's.rst
- docs/writing-a-locustfile.rst
Hey there,
First, thanks for your nice project :).
While reading the documentation, I found a few typos or missing punctuation, and thought you might want to receive a pull request for these.
Cheers,
Xavier
PS: I read the contributing.md, but it does not seem to apply to changes to the documentation?
> Minor edits to the documentation

- docs/tasksets.rst
- docs/writing-a-locustfile.rst
- locust/argument_parser.py
- locust/clients.py
- locust/test/test_locust_class.py
- locust/test/test_runners.py
- locust/user/sequential_taskset.py
- locust/user/task.py
Make it real obvious what is the problem, so that we avoid confusion, like this: https://stackoverflow.com/questions/73093739/how-to-make-locust-test-my-api-endpoint-served-with-fastapi
> Better error message when User.task is set instead of User.tasks

- locust/test/util.py
- locust/web.py
Fix for the following bug: https://github.com/locustio/locust/issues/2147
The `web.py` change is obviously the fix, but without the changes to `uitl.py`, **test_index_with_https** has errors with python 3.7 & 3.8: https://github.com/mikenester/locust/runs/7642011804?check_suite_focus=true
```
Traceback (most recent call last):
File "/home/runner/work/locust/locust/locust/test/test_web.py", line 463, in tearDown
super().tearDown()
File "/home/runner/work/locust/locust/locust/test/testcases.py", line 1[88](https://github.com/mikenester/locust/runs/7642011804?check_suite_focus=true#step:9:89), in tearDown
clear_all_functools_lru_cache()
File "/home/runner/work/locust/locust/locust/test/util.py", line 88, in clear_all_functools_lru_cache
wrappers = [a for a in gc.get_objects() if …
```
> Fix for Flask 2.2.0 breaking changes

- locust/runners.py
- locust/test/test_runners.py
> fix: Ensure new test starts with specified number of users after previous test has been stopped

- locust/runners.py
A continuation of https://github.com/locustio/locust/pull/2155
Consistently uses the word "worker" instead of "client" in the logs (although there remains a lot of places with "client" or "node" in the code)
> Include worker_index in worker connection logging, and stop using the word "client" for what is actually a worker

- locust/main.py
- locust/test/test_main.py
- locust/util/load_locustfile.py
Useful if multiple locustfiles are passed and one imports a User from the other. Improve some logging.
> Allow multiple definitions of same user class name if they come from the same place

- docs/running-distributed.rst
The example inconsistently labeled worker and master in the comments and/or registered the wrong messages to the wrong runners.
> Example had inconsistent labeling

- locust/test/test_web.py
- locust/web.py
fix the problem userclasses missing issue when edit the load test
> fix: edit load test missing the userclasses data

- locust/static/css/application.css
- locust/templates/index.html
Fix these issues:
* When you startup the locust web page first time, in the main page, we cannot open the about page when click the bottom link "About"
* In the "Start new load test" and "Edit running load test" page, the top left close button is not formatted correct(disorderred) , so I corrected the close link position to the same as in the "About" dialog page. see the following screenshot:
1. Modified screenshot, which can show the "About" dialog in the startup page:
2. The "close" button in the "Start new load test" dialog page:
2. The "close" button in the "Edit running load test" dialog page:
> fix(style): about dialog cannot be opened in the startup page 

- setup.cfg
Not really a strict requirement, but older versions have a couple of issues I dont want people to have to encounter.
> Bump FastHttpUser/geventhttpclient dependency to 2.0.2

- docs/custom-load-shape.rst
- examples/custom_shape/staging_user_classes.py
- locust/dispatch.py
- locust/runners.py
- locust/shape.py
- locust/test/test_dispatch.py
Hey Locust Team,
I've been using locust for a while now, and really like to work with it. Still we achieved to run into some shortcomings for the project I am currently working on.
The possibility to create custom LoadTestShapes, where a step / tick only creates a specified set of users.
In our Testscenario we need to make sure that a certain amount of locust users is definitely present upfront. Trying to achieve this with `weighting` or `fixed_users` is possible but from my experience also mixed with a bit of luck. As we are already using `LoadTestShapes` I asked myself, whether it is possible to include the users in the stages for example.
Using this would look like this for example:
```python
stages = [
{"duration": 60, "users": 10, "spawn_rate": 10, "user_classes": [WebsiteUserA]}, …
```
> ft: LoadTestShapes with custom user classes 

- locust/test/test_web.py
- locust/web.py
Steps:
1. run the locust with command `-f a_file_folder/` the `locustfile` argument is a folder, so in the main.py it will return `locustfile` as `None`
2. When start the test, then the web page title `Locust for None` shows, we need to correct the `locustfile` variable at this situation
> fix: when run from web with `-f a_file_folder/` caused page title is None as  `locustfile` argument is None

- locust/test/test_web.py
- locust/web.py
Fix for https://github.com/locustio/locust/issues/2192
When `user_classes` is in the `/swarm` payload, `swarm` will update `environment.parsed_options.user_classes` to include the selected user_classes
> Fix parsed options user classes when using class picker

- locust/stats.py
Added get_stats_summary and get_percentile_stats_summary . This will return the stats as string , So that the string can be used in other places. I am using this to record it in Reportportal.
currently print_stats and print_percentile_stats functions are directly record the result into console_logger. But these functions return the same results into string so that it can be used by other log handler
> stats summary refactoring

- locust/web.py
Second fix for https://github.com/locustio/locust/issues/2204.
As it turns out, the `_reset_users_dispatcher` method isn't necessary. It was originally used for resetting the runners when `user_classes` is in the `/swarm` payload, since I was seeing issues if I didn't do this when originally developing the class picker. My guess is that I updated `_update_user_classes` at some point during that feature and it was the actual fix for the errors I was seeing.
> Second fix for --class-picker resetting user_count on edits

- locust/runners.py
This PR is the conclusion of #2208. 
It deletes the `CustomMessageListener` class for type consistency and adds `Callable` type hint instead.
> Delete the `CustomMessageListener` class for type consistency

- locust/env.py
Improves documentation to avoid misuse of the `parsed_options` argument to `Environment`.
See #2243
> Update documentation for Environment.parsed_options

- docs/running-in-docker.rst
I struggled with several errors using the supplied Docker commands on Windows using WSL, so I have added an alternative Docker command that gave the desired result.
> Added a better working docker command for Windows users

- docs/extending-locust.rst
Does this documentation update also require the changelog generation? (https://github.com/locustio/locust/blob/b64b9a6082451be74f94bf96406315fa819fcd1c/.github/CONTRIBUTING.md)
Thank you.
> bug. Small fixes to documentation

- locust/runners.py
- locust/test/test_runners.py
> Handling zmq corrupted message

- locust/exception.py
- locust/rpc/zmqrpc.py
- locust/runners.py
- locust/test/test_runners.py
#2260
Follow up - restore reconnect when client_id is known
> Fix: Ask worker to reconnect if master gets a broken RPC message

- docs/testing-other-systems.rst
- examples/grpc/hello_server.py
- examples/grpc/locustfile.py
It's better to use interceptor instead of old approach described in old example
I'm using suggested interceptor and it's working pretty good.
> GRPC example - rewrite using interceptor

- docs/running-cloud-integration.rst
> remove typo in running cloud integration docs

- setup.cfg
Fix for #2279
Change packages directive in setup.cfg to use find_namespace: and add [opptions.package_data] for including HTML templates and static files.
This fixes a SetuptoolsDeprecationWarning when running setup.py build.
> Fix setuptools deprecation warnings

- locust/argument_parser.py
- locust/log.py
- locust/main.py
- locust/stats.py
- locust/test/test_main.py
I extended the cli with a `--json` argument. This argument prints the result of a run in json, after a run is finished. It blocks other INFO logs, so it's easy to interoperable with other programs. Below is an example with `jq`
```shell
❯ python -m locust -f examples/locustfile.py --host http://localhost:80 --headless -u 10 -t 4s --json
[
{
"name": "/",
"method": "GET",
"last_request_timestamp": 1670363796.9102132,
"start_time": 1670363793.665749,
"num_requests": 8,
"num_none_requests": 0,
"num_failures": 0,
"total_response_time": 61.882097012130544,
"max_response_time": 18.852641980629414,
"min_response_time": 3.2629000197630376,
"total_content_length": 4920,
"response_times": {
"19": 1,
"9": 1,
"4": 3,
"10": 1,
"3": 1,
"8": 1
},
"num_reqs_per_sec": {
"1670363793": 1,
"1670363794": 2, …
```
> Stats in json to stdout

- examples/use_as_lib.py
Add events when initialize `Environment(user_classes=[MyUser], events=events)`, otherwise the event codes in the example(as following) won't work
```python
env.events.init.fire(environment=env, runner=runner, web_ui=web_ui)
```
> add events when initialize Environment

- docs/running-in-docker.rst
locustio/locust#2188 
- Update `Running a distributed load test on Kubernetes` docs section to include Locust Kubernetes Operator. 
- Small reformat of the section to clearly list all possibilities (HELM & Operator)  in a structured manner.
> docs (#2188):  Add Locust Kubernetes Operator

- docs/increase-performance.rst
3.11 is capable of ~25% more requests/s than 3.9, but only marginally better than 3.10.
> Update performance estimates for modern Python and hardware

- locust/static/chart.js
Resolves https://github.com/locustio/locust/issues/2307.
This prevents the "Download as PNG" text, which displays when hovering over the download icon, from getting cut off.
This is achieved by placing the label to the left of the icon instead of below the icon.
Before:
After:
> Prevent Download as PNG text from getting cut off

- locust/event.py
- locust/runners.py
- locust/test/test_fasthttp.py
- locust/test/test_http.py
Even thought they are deprecated (since 1.5) the documentation sometimes causes confusion, so I think it is time to remove them.
> Remove request_success and request_failure event handlers

- docs/configuration.rst
- locust/argument_parser.py
- locust/html.py
- locust/main.py
- locust/static/locust.js
- locust/stats.py
- locust/templates/index.html
- locust/templates/report.html
- locust/templates/stats_data.html
- locust/test/test_main.py
- locust/web.py
Added --percentiles command line argument which is for response time chart in chart page and download report page.
Default value is 95% and 50%. 
example . # locust -f locust_file.py --percentiles 0.99,0.8
This is from issue [#2311](https://github.com/locustio/locust/issues/2311)
> Add PERCENTILES_TO_CHART param in stats.py to make the Response Time Chart configurable

- README.md
Rename link text on README.md
* Rename link text from Slack signup to locustio.slack
* This link mainly directs to locustio.slack instead of Slack signup.
> Rename link text on README.md

- Makefile
- README.md
- codecov.yml
- docs/developing-locust.rst
- tox.ini
They nuked the package from pypi, breaking thoustands of people's builds!
https://about.codecov.io/blog/message-regarding-the-pypi-package/
> Remove codecov from build

- locust/event.py
- locust/runners.py
- locust/test/test_runners.py
Fired on master whenever a worker connects.
It will be used by locust-plugins Timescale listener.
> Add worker_connect event

- docs/index.rst
RIght now in https://docs.locust.io/en/latest/ the edited titles are shown duplicated:
> Duplicated titles

- locust/dispatch.py
- locust/test/test_dispatch.py
I currently do not have not a local configured unittests, so this is WIP MR for checks.
> Fixed the users dispatching when it got infinite loop (issue-2345)

- locust/stats.py
I believe the comment is wrong, `total_content_length` is used to sum up the content length of the response, not the request, see for example https://github.com/locustio/locust/blob/7002fb72de84f707defbcf5e183013de08f443ba/locust/runners.py#L133C1-L136
> Clarify documentation string for `total_content_length`

- locust/argument_parser.py
- locust/test/test_parser.py
This pull request introduces an improvement to Locust, enabling the specification of `user_classes` through the `LOCUST_USER_CLASSES` environment variable. Currently, `user_classes` can only be defined via command-line arguments, limiting flexibility. With this enhancement, users can conveniently configure a list of user classes separated by spaces, making it easier to simulate specific user behaviors when running Locust in a Docker container.
**Details:**
In the existing implementation of Locust, when executing it within a Docker container, `user_classes` must be specified using command-line arguments. This approach can be cumbersome, requiring modifications to the command every time different user classes need to be tested. This pull request addresses this limitation by introducing …
> Allow selecting user classes using LOCUST_USER_CLASSES env var

- locust/debug.py
- locust/test/test_debugging.py
HttpUser needs the host parameter but if not set directly it was not passed to the user class in `run_single_user` method like it is in runners.
> Fix passing host to user class when debugging

- docs/extending-locust.rst
- examples/add_command_line_argument.py
- locust/argument_parser.py
- locust/static/css/application.css
- locust/templates/index.html
- locust/test/test_web.py
Addresses #2371 
This adds web UI support for a dropdown list in custom arguments:
Code:
```
parser.add_argument("--env", choices=["dev", "staging", "prod"], default="dev")
```
argparse already checks those choices on command-line args, this PR just makes the web UI behave similarly.
The CSS width is different for select (340) vs input (set to 328, actual 340) to get them to be the same actual width. I'm not exactly sure why but it looks like it has to do with differences in how padding is handled between the two tags.
I ran locally with `scripts/run-local-web.sh` on OS X in a virtual env with Python 3.11.3
I wasn't able to get the tox tests running locally (I tried on master before making changes but it failed). Sorry about that! Hopefully the github actions aren't too burdensome.
> Web UI dropdown for custom args with choices

- docs/api.rst
the old dot org has been gone for some while, and everything links to readthedocs these days.
also, the library is called requests, not python-requests.
> update links to requests homepage

- locust/main.py
- locust/test/test_main.py
To be honest this is probably more of a bandaid solution, but for dealing with `KeyboardInterrupt`  this is hopefully sufficient. I've added an integration test that raises a `KeyboardInterrupt`. The logic being that if properly handled, the test will end properly, `@events.test_stop.add_listener` will execute, and a report will be generated.
> Fix #1910 KeyboardInterrupt with load shapes

- locust/__init__.py
... without having to do `import locust_plugins` in every locustfile.
> Import locust_plugins if available to give access to its custom arguments

- locust/main.py
In some cases (such as the default settings in Debian Linux) the hard limit for open files is much higher than the minimum open files limit of 10000. By respecting this hard limit instead of requesting an infinite number of open files this allows us to set the open files to 10000, when attepting to set it to unlimited will fail.
> Respect hard limit when setting open file limit (NOFILE)

- Dockerfile
Bumped python version for official locust Dockerfile.
> chore: bump dockerfile to 3.11-slim base image

- docs/custom-load-shape.rst
- locust/shape.py
- locust/test/test_load_locustfile.py
- locust/util/load_locustfile.py
This PR improves the abstract custom base shape detection by using the same pattern than the base `User` class: abstract base classes should define the `abstract`attribute to `True`.
This change is entirely backward compatible and tested.
This PR fixes the following case:
- define a reusable `LoadTestShape` in your common modules (let's say `lib.BaseShape`)
- create a locust file, create a child shape (cf. below)
- run the bench
This will result in:
- without this change, the imported base class is picked as shape, the child class is ignored.
- with this change, the imported abstract base is ignored and the child class is selected as shape
`lib.py`
```python
class BaseShape(LoadTestShape):
abstract = True
some_class_attr = None # to be provided by child implementation
def tick(self):
``` …
> feat(shape): support user base custom load shape

- docs/custom-load-shape.rst
- locust/main.py
- locust/runners.py
- locust/shape.py
- locust/templates/index.html
- locust/test/test_main.py
- locust/test/test_web.py
- locust/web.py
Currently, it is not possible for a custom `LoadTestShape` to reuse the built-in `run_time`, `num_users` and `spawn_rate` parameters, even if they need/use it (they are rather classical load testing parameters).
There must be an undocumented reason somewhere for this choice.
This pull request allows custom `LoadTestShape` to reuse those command line parameters if explicitly told with the `reuse_parameters` attribute.
So with this change, the following code will work:
```python
class MyCustomShape(LoadTestShape):
reuse_parameters = True
def tick(self):
expected_run_time = self.runner.environment.parsed_options.run_time
...
return None
```
This change is tested, documented and backward compatible. The WebUI swarm form behavior has been adapted to it (`user_count` and `spawn_rate` fields are …
> refactor(shape): allows custom shapes to reuse run-time, spawn-rate and users parameters

- locust/main.py
Python 3.7 is not receiving fixes any more and 3.8 comes with a few nice syntax improvements. So I want to drop support for 3.7 soon. This is just a warning for now, we're still supporting 3.7.
> Log a deprecation warning in Python 3.7

- locust/__init__.py
run_single_user method added to `__all__` variable.
In #1985 run_single_user function was created and was added to top `__init__.py` file in https://github.com/locustio/locust/commit/68f1af3558cf87aa2d99de0daa741780cbeb9e66.
However, it wasn't added to `__all__`.
run_single_user is part of official API (https://docs.locust.io/en/stable/api.html#locust.debug.run_single_userl) and "from locust import run_single_user" statement is used in examples (e.g. [/examples/debugging.py](https://github.com/locustio/locust/blob/master/examples/debugging.py)).
Currently, many linters show warnings like "'run_single_user' is not declared in `__all__`" which may confuse people and make them think that they use Locust incorrectly.
> Add run_single_user to __all__ variable

- docs/installation.rst
- locust/argument_parser.py
- pyproject.toml
[`argcomplete`](https://github.com/kislyuk/argcomplete) adds tab completion for Python CLIs build with the [`argparse`](https://docs.python.org/3/library/argparse.html) module -- [and it works with `configargparse` as well.](https://github.com/kislyuk/argcomplete/issues/123)  This pull request sets up the Locust CLI to use `argcomplete` if it's installed, but if it's not installed, users can still use the Locust CLI without tab completion. In addition, this PR adds an "extra" requirement named "completion", so if users run `pip install locust[completion]`, then Pip will install Locust _and_ `argcomplete`.
> Support argcomplete as an optional dependency

- locust/user/users.py
- locust/user/wait_time.py
It incorrectly assumed the first iteration was instantaneous (because it had no way of knowing when the first iteration started), thus making the first sleep longer than it should be.
Fixes #2427
> Fix too long first wait time for constant_pacing (and constant_throughput)

- locust/runners.py
The current version of condition is hard to read, so I've simplified it.
> refactor(MasterRunner): simplify condition in check_stopped

- docs/installation.rst
- locust/argument_parser.py
- pyproject.toml
It was broken and didnt get fixed. Was never part of a release.
> Revert support for argcomplete

- locust/main.py
- locust/static/css/application.css
- locust/templates/index.html
- locust/test/test_load_locustfile.py
- locust/test/test_web.py
- locust/util/load_locustfile.py
- locust/web.py
Fix for https://github.com/locustio/locust/issues/2412
I also included a legacy UI styling fix. The UserClass and ShapeClass selectors were quite thin.
> Fix for UserClass picker not loading all available Shape Classes

- locust/contrib/fasthttp.py
self.encoding requires a str value. request util can return None which throws 
`TypeError: str() argument 'encoding' must be str, not None`
fixes #2450
> FastHttpUser: encoding return str when response is empty

- examples/terraform/aws/main.tf
- examples/terraform/aws/provisioner.tf
- examples/terraform/aws/variables.tf
Hi,
This is a very small detail, but I think it makes the Terraform module a bit easier to use.
In Terraform, if there is a setting which the typical user should probably adjust, or consider adjusting, the place to put that is `variables.tf`. 
By reviewing `variables.tf` you see a list of configurations to modify.
In this case, `ssh_export_pem` and `aws_region`. I needed to modify them as likely most users would also.
> Add terraform variables

- locust/runners.py
- locust/test/test_runners.py
When developing a custom `TestShape`, a developer needs to implement `tick()` method, that manages `Users` spawning. As mentioned in the [official documentation](https://docs.locust.io/en/stable/custom-load-shape.html#custom-load-shapes):
> Locust will call the tick() method approximately once per second.
Therefore, a developer may design a `TestShape` with a strong assumption that the number of `Users` will be adjusted with ~1 second interval. Unfortunately, the interval is indeed kept only when no adjustment in `Users` number is made - hence it seems useless, as any interval is meaningful only during some changes. Here's an example of logs from Locust master when a custom `TestShape` was implemented and  the `tick()` method is clearly triggered too often:
the timestamps of log messages …
> Ensure to wait a second before next `tick()`

- locust/stats.py
> Tiny optimization of StatsEntry._log_response_time

- .github/workflows/tests.yml
- locust/argument_parser.py
- locust/main.py
- locust/runners.py
- locust/test/test_main.py
- tox.ini
Use it to set the number of times to fork the locust process, to enable using multiple CPU cores. Use `-1` to launch one process per CPU core in your system. Combine with --worker flag or let it automatically set --worker and --master flags for an all-in-one-solution.
Consider it experimental for now, but it looks promising.
> Add --processes parameter to automatically fork subprocesses

- pyproject.toml
While older versions of our dependencies *may* work, we dont really test them, and they could have security issues or bugs.
We dont require the very latest version of everything, to ensure compatibility with whatever other things you might want to use with locust.
> Update minimum version of various dependencies

- locust/main.py
- locust/test/test_main.py
e.g. when the user specified invalid parameters or something
> Fix issue with --processes: Stop parent process from trying to kill children too fast

- locust/argument_parser.py
- locust/main.py
- locust/test/test_web.py
This PR adds the functionality to create any directories provided as part of the --csv / CSV_PREFIX value. e.g. `--csv=some/path/to/my_prefix`.
> Create any directories as part of the CSV Prefix

- locust/test/test_interruptable_task.py
- locust/user/task.py
The #2402 introduced change which wraps `on_stop` call around try/except block inside handling of `InterruptTaskSet` exception.
The initial implementation assumed that every exception shall be handled and logged, without any further consequences. 
This appeared to be a little bit too greedy. It allowed the execution to carry on. 
When running our unit tests we observed a situation where the execution falls into infinite loop. This was because our `on_stop` method implementation counted its invocation and was supposed to raise `StopUser` exception after reaching some arbitrarly chosen number.
We do believe that this behavior is inappropriate, as `StopUser` is supposed to always stop execution of current user.
We wanted to propose a solution for this issue presented in this Pull Request. …
> Apply patch for handling `InterruptTaskSet` exception

- locust/main.py
This would previously result in an error being raised
e.g.
```python
import os
os.path.exists('') # False
os.makedirs('') # FileNotFoundError: [Errno 2] No such file or directory: ''
```
my bad
> Fix an edge case when no directory is part of csv-prefix

- locust/test/test_interruptable_task.py
Fixing minor type hint issue introduced in #2486.
(collections.defaultdict support subscripting ([]) since version 3.9)
> fix(typing): typing.DefaultDict in test_interruptable_task.py

- locust/log.py
- locust/test/test_main.py
Otherwise it would typically be critical, which makes what is probably a user induced exit sound like a crash. 
Add test case.
> Change logging of call to sys.exit() to info level

- locust/contrib/fasthttp.py
If no response headers are present or do not contain response encoding, use charset_normalizer.detect to detect the encoding from response content bytes.
> FastResponse: Detect response text encoding when no information is present on the response headers.

- locust/contrib/fasthttp.py
> Further relax FastHttpUser's host checking to match HttpUser's

- locust/contrib/fasthttp.py
FastHttpUser fails the request if the response can't be converted to text. For example, if the response headers have application/octet stream as response header there is no proper encoding to convert it back to text.
This PR allows the request to succeed by, 
1. Check response.content is null for failure
2. Before attempting to convert to text check if encoding is not None.
(We shall log warning to prompt that response cannot be converted to text and will not be available as a json)
> Fixed response failure for unsupported encoding

- locust/webui/src/components/LineChart/LineChart.test.tsx
- locust/webui/src/hooks/tests/useSwarmUi.test.tsx
- locust/webui/src/test/mocks/statsRequest.mock.ts
- Use mock timers in the `useSwarmUi` test to avoid false test failures
- Remove the dependency on `waitFor` in favor of `runAllTimersAsync`
> Fix useSwarmUi Test with Mock Timers

- pyproject.toml
A previous PR introduced charset_normalizer as a dep, but did not explicitly add it to the pyproject.toml file.
This causes a breaking change on import.
So this PR explicitly includes it.
Resolves #2505
> Add charset_normalizer dependency

- pyproject.toml
A different sort of fix for #2505
> Bump Requests to 2.26.0, remove explicit dependency on charset_normalizer

- locust/rpc/zmqrpc.py
- locust/test/test_zmqrpc.py
This is a follow up for PR https://github.com/locustio/locust/pull/2290.
The solution is based on http://api.zeromq.org/4-2:zmq-setsockopt. 
> Set the IPv6 option for the socket. A value of 1 means IPv6 is enabled on the socket, while 0 means the socket will use only IPv4. When IPv6 is enabled the socket will connect to, or accept connections from, both IPv4 and IPv6 hosts.
The test is done with kind for 3 env, ipv4 only, ipv6 only and dual stack. With help of https://abdelrhmanhamouda.github.io/locust-k8s-operator/
Test result:
ipv4-only  before-patch(success) after-patch(success)
ipv6-only before-patch(fail, the worker can't connect with master) after-patch(success)
dualstack before-patch(success) after-patch(success)
> Support IPv6 for zmq connection between master and worker

- locust/user/task.py
fixes #2532 
---
Setting the initial value for `_cp_last_run` inside the `TaskSet` initializer.
Thus the attribute will not be missing when being called inside the `constant_pacing` wait time strategy.
Similar to what is happening in the `User` class.
> setting initial _cp_last_run on TaskSet in order to allow constant_pacing wait time strategy

- locust/env.py
- locust/test/test_web.py
- locust/web.py
a shape class' `.runner` member is set by `_create_runner` method of `Environment` class. However, when the UI picker is used, the `shape_class` member of an `Environment` instance is not initialized yet, hence, there's no `Runner` assignment on initialization. Therefore, if you'd like to refer to `self.runner` in your custom test shape (for instance to get the number of users running), you receive an error saying that `self.runner` is `None`. 
Hence, I added the shape class `runner` initialization also when the shape class is selected with UI picker.
> Update shape class' runner when Web UI picker is used

- .git-blame-ignore-revs
- locust/argument_parser.py
- locust/clients.py
- locust/contrib/fasthttp.py
- locust/debug.py
- locust/dispatch.py
- locust/env.py
- locust/event.py
- locust/input_events.py
- locust/main.py
- locust/rpc/protocol.py
- locust/runners.py
- locust/shape.py
- locust/stats.py
- locust/test/mock_logging.py
- locust/test/test_dispatch.py
- locust/test/test_web.py
- locust/user/inspectuser.py
- locust/user/task.py
- locust/user/users.py
- locust/util/load_locustfile.py
- locust/web.py
- pyproject.toml
- tox.ini
1. Mypy: check typing compatibility for the oldest supported Python version - currently Python3.8.
2. Fix mypy errors, add from \_\_future__ import annotations & upgrade type annotations using fix-future-annotations.
3. Upgrade mypy, set types-requests as mypy test dependency in tox.
> Fix mypy configuration & upgrade typing

- .git-blame-ignore-revs
- benchmarks/dispatch.py
- locust/dispatch.py
- locust/runners.py
- locust/user/task.py
- pyproject.toml
1. Set python target-version for ruff.
2. Enable FA102 rule (Checks for uses of PEP 585- and PEP 604-style type annotations in Python modules that lack the required from __future__ import annotations import for compatibility with older Python versions).
3. Enable pyupgrade rules.
4. Make code compatible with rules.
> Ruff set python version and enable more rules

- locust/main.py
When starting with --processes, call gc.collect() and (most importantly) gc.freeze() before forking to reduce copy-on-write due to ref count updates
> Optimize memory usage when using --processes

- locust/stats.py
- locust/test/test_runners.py
because it is faster, and more readable
> Use defaultdict:s for stats dictionaries instead of setdefault

- locust/test/test_load_locustfile.py
- locust/util/load_locustfile.py
If the locustfile is called "locust.py" it collides with the locust module during import, but it can be worked around (this used to work before https://github.com/locustio/locust/pull/2576)
> Work around issue with locustfiles named "locust.py"

- docs/quickstart.rst
- docs/running-without-web-ui.rst
> Fixed typos in documentation

- locust/argument_parser.py
- locust/runners.py
- locust/test/test_main.py
also some other minor locustfile downloading related fixes
> Change download-from-master to use temp file dir

- locust/dispatch.py
- locust/env.py
- locust/runners.py
- locust/test/test_dispatch.py
- locust/test/test_env.py
- locust/test/test_runners.py
- locust/test/util.py
superseeding #2568, coming from discussion in #2522.
this PR makes it possible to implement custom dispatcher logic and specifying the dispatcher class when creating an `Environment`.
a little unsure and not really satisfied with the name of the "interface" `UserDispatcherType`.
played around with `UserDispatcherBase` (but it's [discouraged](https://softwareengineering.stackexchange.com/questions/422970/does-using-the-word-base-in-a-class-name-indicate-abstraction)to use `Base`). `IUserDispatcher` doesn't feel pythonic. so any suggestion on a better name is welcomed :) my top choice would be to rename `UserDispatcher` to `WeightedUserDispatcher` (or similar) and have the interface changed to `UserDispatcher`, but at the same time I wanted to make as few changes as possible.
some methods …
> pluggable dispatcher logic

- docs/configuration.rst
- locust/argument_parser.py
- locust/test/test_parser.py
- pyproject.toml
- tox.ini
**Issue Addressed:**
This PR implements support for TOML files as configuration files and sets [pyproject.toml](https://packaging.python.org/en/latest/specifications/pyproject-toml/#pyproject-toml-spec) as the default. It addresses the #2298 issue.
**Implementation Details:**
1. Used the built-in `CompositeConfigParser` with `TomlConfigParser` and `DefaultConfigFileParser`, which allow the [configargparse](https://github.com/bw2/ConfigArgParse) lib to automatically parse options from defined `.conf` and `.toml` files. 
2. Added `pyproject.toml` to `DEFAULT_CONFIG_FILES`. 
3. Introduced a new project dependency - [toml](https://github.com/uiri/toml), which is required for the `configargparse` TOML parser to work. 
4. Added tests to check the correct parsing of `.conf` and `.toml` …
> Implement pyproject.toml support for Locust configuration

- locust/contrib/fasthttp.py
> Dont throw an exception in FastHttpUser if a request is made with stream=True and the connection fails

- locust/contrib/fasthttp.py
- locust/test/test_fasthttp.py
This reverts commit 7ce89a00 and improves it for cases when `stream=True` and `catch_response=True`. Together with #2642, this finally makes handling long-running streaming requests possible and reporting a failure while consuming the response.
The problem is that calling `response.content` triggers a `read` of the whole response eventually, rendering subsequent (streaming) reads pointless.
> Do not call blocking `content` property and lazily load response

- docs/running-distributed.rst
- examples/custom_messages.py
- locust/runners.py
- locust/test/test_runners.py
This MR adds the functionality to `Runners.register_message` to register a `concurrent` function.
Issue #2608 explains this PR in more detail.
> Add functionality to run listener functions for `custom_messages` concurrently

- locust/env.py
- locust/runners.py
- locust/test/test_env.py
- locust/test/test_web.py
When updating the user class, send a message to workers (if in distributed mode) to update their user classes as well
In distributed mode
fixes #2657
> Update User Classes in Distributed Mode

- locust/dispatch.py
- locust/test/test_dispatch.py
> fix(dispatch): UserClasses weight distribution with gcd

- .pre-commit-config.yaml
- benchmarks/dispatch.py
- locust/dispatch.py
- locust/rpc/protocol.py
- locust/runners.py
- locust/test/mock_locustfile.py
- locust/test/test_dispatch.py
- tox.ini
1. Removing deprecated mypy "# type: ignore" comments.
2. Pinning the same version of ruff in .pre-commit-config.yaml and tox.ini files.
3. Ruff 0.3.7 compatibility.
> Small cleanup: mypy type-ignore and dev deps

- locust/main.py
- locust/util/timespan.py
As discussed [here](https://github.com/locustio/locust/issues/2683)
> Allow worker process to run with --run-time specified, just log a warning

- locust/test/test_runners.py
- locust/user/task.py
> Use deque for tasks in taskset instead of plain list

- locust/html.py
Replace deprecated datetime.datetime.utcfromtimestamp function with datetime.datetime.fromtimestamp.
See datetime.datetime.utcfromtimestamp [docs](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp):
> **Warning:** Because naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. As such, the recommended way to create an object representing a specific timestamp in UTC is by calling datetime.fromtimestamp(timestamp, tz=timezone.utc).
> Deprecated since version 3.12: Use [datetime.fromtimestamp()](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) with [UTC](https://docs.python.org/3/library/datetime.html#datetime.UTC) instead.
It currently …
> refactor: replace deprecated utcfromtimestamp function

- locust/input_events.py
WindowsKeyPoller.captured_chars uses methods responsible for removing at beginning and appending at end.
collections.deque performs those in constant time, in contrast with list (linear time for appending/removing at beginning).
Replaces  #2431
> refactor(WindowsKeyPoller): change implementation of captured_chars 

- locust/contrib/fasthttp.py
- locust/runners.py
- tox.ini
Before (mypy checks in CI):
```
mypy: commands[0]> mypy locust/
locust/stats.py:209: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
locust/stats.py:210: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
locust/runners.py:600: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
locust/runners.py:661: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
locust/runners.py:663: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs …
```
> annotate return types of a few functions to enable more mypy check

- locust/web.py
Hit a bug where, by using a custom `LoadTestShape` with `use_common_options` (as described [here](https://docs.locust.io/en/stable/custom-load-shape.html#reusing-command-line-parameters-in-custom-shapes)) noticed that the `run_time` set through the web UI is **not** persisted to `parsed_options` (which I'd be accessing from my custom shape class' `self.runner.environment.parsed_options.run_time`). This value was thus always grabbing the initial value set through config / cli options, which is pretty unexpected to me. I understand the intended use case here, as specified in the docs, is to "reuse command line parameters", but since the web UI still allows changing this value updates should IMO reflect everywhere they're referenced downstream.
Persist this value to `parsed_options_dict` on …
> fix: update `parsed_options` `run_time`

- locust/html.py
- locust/stats.py
Because of `HISTORY_STATS_INTERVAL_SEC`, we will only have history starting after 5 seconds of run time. Unlike `request_stats` in `web.py`, we rely on history to display the charts in the HTML report. This is why the dashboard shows the results correctly in the dashboard but not in the report
Expose a new function `update_stats_history` that can be called when generating the HTML report. This will ensure that the stats history list is up to date before returning the report
Fixes #2706
> Update Stats History on HTML Report

- locust/rpc/zmqrpc.py
> Dont enable ipv6 for zmq if no ipv6 stack exists

- locust/webui/src/components/Table/Table.tsx
Currently when you execute a test with a large number of different endpoints the Table Head doesn't scroll when you scroll down, making the analysis and navigation of the HTML Report and the Statistics tab a pain.
closes #2688 
- Applied sticky positioning to the TableHead to ensure it remains at the top of the viewport.
- Ensured the TableContainer allows the sticky positioning by setting overflow-X to visible.
<details>
<summary> Statistics Tab </summary>
https://github.com/locustio/locust/assets/107027346/dba3f574-2ffe-46c9-b4d3-59da0c089625
</details>
<details>
<summary> HTML Report </summary>
https://github.com/locustio/locust/assets/107027346/b592dfbc-36e3-4694-a3e0-760b2645aaa9
</details>
> Pin the headers to the top of the window

- examples/semaphore_wait.py
- locust/event.py
- locust/runners.py
- locust/test/test_runners.py
Ever since 2.0 the behaviour has been really strange: spawning_complete _on workers_ was fired after every cycle instead of only once.
This restores the functionality by having the masters spawning_complete event send a message to workers. 
Technically a breaking change.
> Ensure spawning_complete only happens once on workers

- locust/web.py
Should help with issues like this one #1142
> Improve confusing log messages if someone accidentally accesses the Web UI over HTTPS

- docs/requirements.txt
Upgrade Sphinx to something current.
I skimmed through the Sphinx changelog from 4.3.2 to 7.3.7 and didn't find anything particular noteworthy that might require project changes. 
I also clicked around the docs build with the new versions, and things looked ok.
Doesn't look like I need to update anything else to get this merged, but if there is please let me know.
> Upgrade Sphinx to latest version (7.3.7)

- docs/conf.py
- docs/requirements.txt
I think [088105c](https://github.com/locustio/locust/pull/2736/commits/088105c9ba28587b4c64b8f86becc589deaf8ec1) is the main culprit here. 
I could test in isolation, but I think the other changes make sense also.
> Fix sphinx and theme upgrade

- locust/argument_parser.py
This one is a bit tricky, the argument parser happens before the log setup, so we don't have access to the same log levels as we would in the rest of the application. I also didn't want to have tons of messages logging for no reason, so I placed the messaging outside of the while loop. 
The problem with having the message outside of the while loop, is that we don't yet know if connecting to master failed or not (so it shouldn't _really_ be a warning). However, without logging being setup it seems we only have warning level logs. So the warning level is a bit of a lie, but it does at least provide some feedback that the master needs to be connected in order for the worker to start
Fixes #2748
> Add Logging to download_locustfile_from_master

- locust/web.py
Some of our users are encountering MIME type issues on Windows operating systems. According to a post on [StackOverflow](https://stackoverflow.com/questions/59355194/python-flask-error-failed-to-load-module-script-strict-mime-type-checking-i), this issue could be related to the operating system. This should fix the issue and ensure the correct MIME type is set.
**Note**: I am currently unable to reproduce this issue and therefore am unable to test that this solves the issue
Fixes #2753 #2633
> Add JavaScript to MIME types for Windows Operating Systems

- docs/use-as-lib.rst
- locust/__init__.py
1. Add a condition to the `__init__.py` that will skip monkey patching when `LOCUST_SKIP_MONKEY_PATCH` is set
2. Update `use-as-lib` to document disabling monkey patching
Tested using Locust as a lib with boto3
Fixes #2250
> Option to Skip Monkey Patching with LOCUST_SKIP_MONKEY_PATCH

- locust/contrib/fasthttp.py
A few minor FastHttpSession improvements, including adding json as positional argument to `def post(self, url, data=None, json=None, **kwargs):` function.
> A few minor FastHttpSession improvements

- locust/contrib/fasthttp.py
The aim of this PR is to provide better typing annotation support for `class FastHttpUser`.
Fixes #2563. Follow-up to  #2699.
> FastHttpSession requests typing 

- examples/test_data_management.py
- locust/event.py
- locust/runners.py
- locust/test/test_runners.py
when troubleshooting a problem where workers did not receive a heartbeat from master within `locust.runners.MASTER_HEARTBEAT_TIMEOUT` (not a locust problem) i created two new events which made it possible to easily update our statistics listener to send that information influxdb.
- `heartbeat_sent`: fired when master `sent` heartbeat to a worker
- `heartbeat_received`: fired when worker `received` said heartbeat
- `usage_monitor`: fired with information about current CPU and memory usage every `locust.runners.CPU_MONITOR_INTERVAL`
i did considered creating a custom `on_master_report` to add worker CPU and memory usage there, but that would leave out master. i also considered using the `heartbeat` event, since CPU and memory is part of the heartbeat RPC message sent, but that would also …
> new events for heartbeat and usage monitor

- benchmarks/dispatch.py
Various improvements to the benchmark to make testing changes easier.
Main changes:
- Disable garbage collector during benchmark.
- Use time.process_time instead of time.perf_counter.
- Run only test case with the highest values by default. Run full test matrix with CL flag. 
- Add possibility to test both: fixed_count Users and weight Users.
- Add possibility to run test cases multiple time with the same arguments.
- Make saving result files optional.
>python benchmarks/dispatch.py --help
```
usage: dispatch.py [-h] [-f] [-i] [-r REPEAT] [-s]
options:
-h, --help            show this help message and exit
-f, --full-benchmark  run benchmark on full test matrix
-i, --include-fixed-users
add test cases when 50 percent of users use User.fixed_count instead of User.weight
-r REPEAT, --repeat …
```
> dispatch benchmark test improvements

- docs/tasksets.rst
- locust/test/test_sequential_taskset.py
- locust/user/sequential_taskset.py
Fixes #2739 
Fixes #2740 
As explained in respective issues,`SequentialTaskSet` now allows task repetition if `tasks` is a dictionary with weight, and `itertools.cycle` is used to iterate over tasks in a cycle.
So far only a draft of backend changes.
Let me know if changes are OK and then I will update also tests and docs.
> Optimize `SequentialTaskSet`

- .github/workflows/tests.yml
- pyproject.toml
Updates publication-specific build logic to correctly generate tag numbers
- Utilise `poetry` version number in steps which generate tags for publication
- Always bump the `patch` version number when creating candidate dev build numbers
- Allow Pull-Request builds to verify the Docker build (removal of `setuptools_scm`)
> Correctly set version from Poetry in published builds

- examples/web_ui_cache_stats.py
After removing the legacy webui, we no longer have to set the static assets for the modern ui. This change should be reflected in the example
> Fix Extend Webui Example

- pre_build.py
This PR makes the pre-build script perform the same steps that the `make` command for building the project does, and provides the same error code where `yarn` is not present.
We try to avoid using `shell=True` and so need to split the command up
> Provide warning for local installs where yarn is not present

- .github/workflows/tests.yml
- Makefile
- docs/developing-locust.rst
- tox.ini
Updates the GH Action tests for Windows/Linux, aiming to produce predictable failures of tests in controlled scenarios (i.e. using the correct Windows package).
Would recommend trying this out though, I still think there's some weird behaviour of some of these process-based tests, where the Windows vs. Linux tests do not operate or fail identically, perhaps this is intended.
I suspect this can be fixed more cleanly by sorting the `venv` mess in the pipeline and having the windows GH Action runner be in the correct, activated `venv` instead of doing this, so will raise a separate issue for that.
Addresses https://github.com/locustio/locust/issues/2796
Some testing of the breaking changes submitted in the issue by @andrewbaldwin44 
- Pass …
> Fix tests on windows

- locust/__init__.py
Fixes #2812
I tested it only with the newest versions of locust and its dependencies.
Currently, I don't know use cases of `os.getenv("LOCUST_SKIP_URLLIB3_PATCH", None)`.
However, this PR touches implementation details of urllib3 and gevent, so I want to provide possibility to opt-out.
(For example, it may fail with future release of urllib3.)
PR is based on this [answer](https://github.com/gevent/gevent/issues/1957#issuecomment-1902063299).
> Avoid deadlock in gevent/urllib3 connection pool (fixes occasional worker heartbeat timeouts)

- .github/workflows/tests.yml
- pre_build.py
- tox.ini
Rights some wrongs currently in `master` relating to Windows integration tests.
In short - this works around some quirks of Poetry on Windows, with respect to the `PATH` and shell commands.
- Ensures that Windows tests run the current version of Locust
- Ensures that the prebuild script runs on the Windows shell (such that it can find `yarn`)
- Re-simplifies the test matrix
> Update poetry windows tests

- locust/main.py
- locust/stats.py
- locust/webui/src/components/StatsTable/StatsTable.tsx
- locust/webui/src/pages/HtmlReport.tsx
**Main stats table**
**HTML report stats table**
> Fix HTML Report Stats Table

- locust/webui/src/components/LineChart/LineChart.tsx
- locust/webui/src/components/SwarmCharts/SwarmCharts.tsx
- locust/webui/src/pages/tests/HtmlReport.test.tsx
> Locust UI Charts Should Change Color Based on Theme

- locust/main.py
- locust/web.py
- locust/webui/src/redux/slice/swarm.slice.ts
- locust/webui/src/test/mocks/swarmState.mock.ts
- Import the locust cloud module if installed to allow for registering custom arguments
- Return the start time from the swarm arguments to help with querying. This could also be useful for us if we ever want to show how long locust has been running for in the UI
> Integrations for Locust Cloud

- locust/dispatch.py
- simplify fixed_count Users generation in UsersDispatcher._user_gen
- minor _kl_generator improvements
Performance impact.
> python benchmarks/dispatch.py --repeat 5 --include-fixed-users
Branch:
```
0001/0010 - 1,000 workers - 1,000,000 users - 1000 user classes - 10,000 users/s - instantiate: 85.078ms - new_dispatch (ramp-up/ramp-down): 9.811ms/10.554ms - cpu_ramp_up: 28.760/21.637/164.883ms - cpu_ramp_down: 15.035/14.403/18.000ms
0002/0010 - 1,000 workers - 1,000,000 users - 1000 user classes - 10,000 users/s - instantiate: 86.416ms - new_dispatch (ramp-up/ramp-down): 10.846ms/10.935ms - cpu_ramp_up: 30.362/16.584/180.464ms - cpu_ramp_down: 7.042/6.700/9.677ms
0003/0010 - 1,000 workers - 1,000,000 users - 1000 user classes - 10,000 users/s - instantiate: 72.248ms - new_dispatch …
```
> Simplify fixed_count Users generation in UsersDispatcher._user_gen

- .github/workflows/tests.yml
Use node 20.x for PyPI release and pre-release
> Github Actions: Use node 20.x (fix PyPI Release and pre-Release Steps)

- locust/webui/src/components/LineChart/LineChart.types.ts
- locust/webui/src/components/LineChart/LineChart.utils.ts
- locust/webui/src/components/LineChart/tests/LineChart.mocks.ts
- locust/webui/src/components/LineChart/tests/LineChart.test.tsx
- locust/webui/src/components/LineChart/tests/LineChartUtils.test.tsx
- locust/webui/src/utils/date.ts
- Use types from echarts to get type hints and ensure we are properly using the API
- Add a failsafe for date formatting (shouldn't ever be an issue but strictly speaking the types don't match so we should have this)
- Add tests for creating echart options
> Add Tests for Web UI Line Chart

- .github/workflows/tests.yml
Ensures that `sdist` tarball contains web UI code, this is necessary for things such as the `brew` installation of Locust.
Example run of `sdist` build and tar unwrap with this added step:
https://github.com/mquinnfd/locust/actions/runs/10271769131
Example `sdist` build without web UI: 
https://pypi.org/project/locust/2.31.1/#files
> Prebuild UI in PyPi publish steps

- locust/webui/src/components/LineChart/LineChart.tsx
- locust/webui/src/components/LineChart/LineChart.types.ts
- locust/webui/src/components/LineChart/LineChart.utils.ts
- locust/webui/src/components/LineChart/tests/LineChart.mocks.ts
- locust/webui/src/components/LineChart/tests/LineChart.test.tsx
- locust/webui/src/components/LineChart/tests/LineChartUtils.test.tsx
- Expose scatterplot support from echarts for the locust webui
> Webui Add Scatterplot Support

- locust/webui/src/components/Layout/Navbar/Navbar.tsx
Minor change that fixes a UI glitch in Navbar.
Before:
After:
> Add missing margin between Logo and Host in Navbar

- .github/workflows/tests.yml
- locust/webui/README.md
- locust/webui/package.json
- locust/webui/src/assets/Logo.tsx
- locust/webui/src/components/Form/Select.tsx
- locust/webui/src/components/Layout/Navbar/Navbar.tsx
- locust/webui/src/components/Tabs/Tabs.constants.tsx
- locust/webui/src/hooks/tests/useFetchExceptions.test.tsx
- locust/webui/src/hooks/tests/useFetchStats.test.tsx
- locust/webui/src/hooks/tests/useFetchTasks.test.tsx
- locust/webui/src/hooks/useCreateTheme.ts
- locust/webui/src/hooks/useFetchExceptions.ts
- locust/webui/src/hooks/useFetchStats.ts
- locust/webui/src/hooks/useFetchTasks.ts
- locust/webui/src/lib.tsx
- locust/webui/src/pages/Auth.tsx
- locust/webui/src/pages/Dashboard.tsx
- locust/webui/src/test/mocks/statsRequest.mock.ts
- Separate the useSwarmUI hook into three separate hooks. This will improve maintainability, performance, and testability. It will also allow for the hooks to be selectively imported and used in library mode as need be
- Add more exports
- Update logo to reduce hook calls and potentially allow for custom theming in the future
- Add steps to prerelease and release to deploy on NPM (tested in a separate repository so we should see these working as expected
- Export tabs as an object rather than an array in library mode for ease of use
- Add more exports from the locust-ui library
- Update locust-ui README
- Deployed a beta version of the locust UI on NPM: https://www.npmjs.com/package/locust-ui
> Web UI as a Library NPM Release

- .github/workflows/tests.yml
- package.json
The publish command needs to be ran in the webui directory. This sets the correct directory
> Webui Fix NPM Publish Step

- .github/workflows/tests.yml
The publish and pre-publish steps need to build the library explicitly before publishing
> Web UI Github Action Publish steps must Build lib

- locust/webui/src/components/Form/Select.tsx
- locust/webui/src/components/LineChart/LineChart.utils.ts
- locust/webui/src/redux/slice/ui.slice.ts
1. Allow the select input size to be controlled
2. Safeguard charts.time, which is possibly undefined when using the Charts component as a library
> Webui Allow changing select input size

- locust/webui/src/components/Form/Select.tsx
Use an intersection rather than interface extension for the select input, such that the MUI select prop types will be properly received
> Correct types for form select

- locust/webui/src/components/LineChart/LineChart.types.ts
- locust/webui/src/components/LineChart/LineChart.utils.ts
- locust/webui/src/components/LineChart/tests/LineChartUtils.test.tsx
The chart may now only be scrolled using the toolbox. When zoomed a slider is also visible, the slider is then removed when zoom is reset. I could not find a way to have scroll zoom when holding the shift button without the mouse scroll event being locked for the charts
> Web UI Remove Scroll to Zoom

- locust/webui/src/hooks/tests/useFetchStats.test.tsx
- locust/webui/src/hooks/useFetchStats.ts
Fixes #2870 
The issue was introduced when we switched the x-axis to type time. On each reload the current timestamp is recorded, causing it to appear as data is still being collected, even after a test stop
> Webui Remove chart initial data fetch

- .github/workflows/tests.yml
[In Progress]
Corrects some problems with pushing docker builds to `latest` and makes debugging pipeline variables like tag numbers easier.
Current issue observed in `master` on this repo seems to be that the short tag number isn't set when creating the Web UI lib, this seems fine on my [fork build here](https://github.com/mquinnfd/locust/actions/runs/10633776749/job/29479755479) so we need to get to the bottom of that
- Adds some async printing of build metadata to the pipeline for debugging
- Only tags docker images as `latest` on tag builds
- Consolidates the "is this a tag build" logic into one place
> Build pipeline tweaks - docker tagging

- .github/workflows/tests.yml
Adds a dependency on the build package step, from the POV of the publishing step.
Apparently, transitive dependencies are not acceptable for Github Actions job outputs, but there's no warning thrown about this during parsing, fun!
> Add publishing dependency on build package step

- examples/rest.py
- locust/clients.py
- locust/contrib/fasthttp.py
- locust/dispatch.py
- locust/event.py
- poetry.lock
- pyproject.toml
[PEP 696](https://peps.python.org/pep-0696/)
> Simplify Generator annotations - PEP 696

- locust/argument_parser.py
`download_locustfile_from_url` parses the locust filename from the URL, but it does not take into account if query parameters are present in the request. This fixes the issue
> Filename from URL Should Strip Query Params

- locust/clients.py
- locust/contrib/fasthttp.py
- locust/runners.py
- locust/stats.py
[Python docs](https://docs.python.org/3/library/typing.html#typing.Any):
> Special type indicating an unconstrained type.
>     Every type is compatible with Any.
>     Any is compatible with every type.
> Remove redundant None in Any | None annotations

- examples/custom_messages.py
- locust/runners.py
This prevents the `custom_messages` example from failing when running locally with `AttributeError`s for `environment.runner.worker_count` and `environment.runner.clients`.
ref: https://github.com/locustio/locust/blob/7c85b7988c643ee8f688c8bb6919272c38fbcf7b/examples/custom_messages.py#L45-L48
> fix: Add more worker info to LocalRunner for parity with others

- locust/webui/README.md
Update the Web UI README to reflect the favicon change
> Update Webui README

- examples/mongodb/README.md
- examples/mongodb/locustfile.py
- locust/contrib/mongodb.py
This is a resubmission/continuation of #2882.
Additions:
- examples/mongodb/README.md
- examples/mongodb/locustfile.py
- locust/contrib/mongodb.py
Updates:
- Updated the event request type and name:
- addressing -> https://github.com/locustio/locust/pull/2882#discussion_r1739637421
- Fixed MongoDBClient:
- addressing -> https://github.com/locustio/locust/pull/2882#discussion_r1739639080
> Add Mongodb test example

- locust/web.py
When the `--web-login` flag is used without a login_manager, we should pass the error from flask_login to communicate that a user or request loader must be set
`Locust auth exception: 'Flask' object has no attribute 'login_manager' See https://docs.locust.io/en/stable/extending-locust.html#adding-authentication-to-the-web-ui for configuring authentication.`
`Locust auth exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info. See https://docs.locust.io/en/stable/extending-locust.html#adding-authentication-to-the-web-ui for configuring authentication.`
> Fix Login Manager Error Message

- .github/workflows/tests.yml
workaround for `/home/runner/work/locust/locust/.venv/bin/tox: /home/runner/work/locust/locust/.venv/bin/python: bad interpreter: No such file or directory`
> Pin python versions to avoid gh caching issue + always Install Dependencies, even when it looks like there was a cache hit

- locust/argument_parser.py
- locust/main.py
- locust/web.py
- Add argument for an optional display name for where the web UI is hosted
- Change log level of 400-404 requests to DEBUG, so they will not be visible by default
> Improve Web UI Logging

- .readthedocs.yaml
Currently the published docs using RTD have the wrong version of Locust during the docs build, because the full Git history isn't there. The `tox` tests previously had this issue when the base checkout didn't pull the whole git history. This results in something like the below:
```
locust -V
locust 0.0.1.dev286 from /usr/local/lib/python3.12/site-packages/locust (Python 3.12.5)
```
This PR updates this based on guidance from RTD's own docs, though it's difficult to actually test that this works without overwriting the current docs 🤔 
RTD docs on this here:
https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-git-clone
> Fix RTD versioning with a deep git clone

- locust/webui/src/components/Form/Form.tsx
- locust/webui/src/components/Layout/Navbar/SwarmMonitor.tsx
- locust/webui/src/components/Reports/Reports.tsx
- locust/webui/src/components/SwarmForm/SwarmEditForm.tsx
- locust/webui/src/components/SwarmForm/SwarmForm.tsx
- locust/webui/src/components/SwarmForm/SwarmUserClassPicker.tsx
- locust/webui/src/constants/swarm.ts
- locust/webui/src/redux/api/swarm.ts
- locust/webui/src/redux/slice/root.slice.ts
- locust/webui/src/redux/slice/swarm.slice.ts
- locust/webui/src/types/swarm.types.ts
- locust/webui/src/types/window.types.ts
- locust/webui/src/utils/object.ts
1. Update swarm form submit to account for the response and display a message if there is a failure
2. Allow for a form change event to be provided
> Add error message to swarm form

- locust/main.py
> Disable --csv for workers when using --processes.

- locust/webui/src/components/ExceptionsTab/ExceptionsTab.tsx
- locust/webui/src/components/LineChart/LineChart.utils.ts
- locust/webui/src/components/SwarmRatiosTab/SwarmRatiosTab.tsx
- locust/webui/src/components/Tabs/Tabs.constants.tsx
- locust/webui/src/hooks/useFetchExceptions.ts
- locust/webui/src/hooks/useFetchStats.ts
- locust/webui/src/hooks/useFetchTasks.ts
- locust/webui/src/pages/Dashboard.tsx
1. The chart tab was not displaying properly if it was the first tab to be viewed after starting a test (e.g. ?tab=chart)
2. The chart tab would briefly show random timestamps. This can be fixed by setting a min value
3. Improve the view of the response percentiles graph by starting it at 0
4. Improve performance slightly by only fetching exceptions and ratios on the respective tabs
> Web UI - Fix Line Chart

- locust/web.py
- locust/webui/src/components/Form/NumericField.tsx
- locust/webui/src/components/StateButtons/EditButton.tsx
- locust/webui/src/components/SwarmForm/SwarmForm.tsx
- locust/webui/src/components/SwarmForm/tests/SwarmForm.test.tsx
- locust/webui/src/types/swarm.types.ts
Fixes #2924
1. Remove reference to `isShape` and replace with `hideCommonOptions`
2. Disable runtime input if `hideCommonOptions` (setting the field has no effect)
3. Disable edit swarm button if `hideCommonOptions` is true, as the only fields that can be edited will have no effect
4. Make user count, ramp up, and host as required fields, and ensure user count and ramp up are using correct formats
> Modern UI - Fix Hide Common Options

- locust/rpc/zmqrpc.py
**Summary of changes:**
Previously IPV6 was enabled if the kernel supported the IPV6 stack.  This was an issue in the distributed scenario when there is a network component between the master and worker nodes that does not support IPV6.  This is the case for example in AWS EKS cluster where the service resource does not support IPV6 even if the pods in the cluster do.  
To avoid attempting to communicate over IPv6 when it is not possible, some basic logic was added  which does the following:
1. Determine as before if the kernel supports IPv6, but uses the socket method, has_dualstack_ipv6().  This does not have the limitations of has_ipv6() of the socket library (and I imagine the reason why it was avoided) since it actually does a syscall to the kernel which will fail if the kernel does …
> Decide if ipv6 can work

- docs/conf.py
- docs/faq.rst
- poetry.lock
- pyproject.toml
Previously ReadTheDocs had built-in support for Google Analytics. This has been removed, and this PR fixes the GA tracking using a Sphinx extension.
> Add Google Analytics to docs.locust.io

- docs/extending-locust.rst
- examples/web_ui_auth.py
- examples/web_ui_auth/basic.py
- examples/web_ui_auth/custom_form.py
- locust/web.py
- locust/webui/src/components/Form/CustomInput.tsx
- locust/webui/src/components/Form/NumericField.tsx
- locust/webui/src/components/Form/PasswordField.tsx
- locust/webui/src/components/Form/tests/CustomInput.test.tsx
- locust/webui/src/components/Form/tests/NumericField.test.tsx
- locust/webui/src/components/Form/tests/PasswordField.test.tsx
- locust/webui/src/components/SwarmForm/SwarmCustomParameters.tsx
- locust/webui/src/pages/Auth.tsx
- locust/webui/src/types/auth.types.ts
- locust/webui/src/types/form.types.ts
- locust/webui/src/types/swarm.types.ts
1. Allow the auth form to be configured with any inputs. The configuration for the inputs use the same API and the same component as the locust custom arguments
2. Added an example of the auth custom form and updated the docs
3. Add tests for the custom inputs, the password input, and the numeric input
4. Custom arguments isSecret field will now have a visibility toggle in the webui
> Webui Add Custom Form to Auth Page

- locust/webui/src/components/LineChart/LineChart.tsx
- locust/webui/src/components/LineChart/LineChart.utils.ts
- locust/webui/src/components/LineChart/tests/LineChartUtils.test.tsx
- If the chart lines change during a render, echarts merges the lines with the existing ones by default. This adds a prop that allows for the lines to be redrawn in the case that they have completely changed
- Remove the isDarkMode prop from drawing marked lines. The marked lines infer their color from the base axis lineStyle, so removing this prop will save us a useEffect cycle
> Webui Echarts Redraw Request Lines if Changed

- docs/extending-locust.rst
- locust/web.py
- locust/webui/src/pages/Auth.tsx
- locust/webui/src/types/auth.types.ts
1. Add type hints for auth args
2. Add "info" to auth args, allowing to display an info message
3. Update docs
> Webui Add Auth Info to Auth Page

- locust/webui/src/components/Form/CustomInput.tsx
- locust/webui/src/pages/Auth.tsx
- locust/webui/src/styles/theme.ts
- Allow Markdown for boolean field
- Allow Markdown for displaying authentication info
> Webui Add Markdown Support for Auth Page

- locust/html.py
- locust/stats.py
- locust/test/test_stats.py
1. Only update stats when a test is running (not before the test starts, not after test stop)
2. The HTML report should update history only up to the test end time
Fixes #2910
> Fix Incorrectly Updating Stat History

- locust/env.py
- locust/log.py
- locust/main.py
- locust/runners.py
- locust/util/deprecation.py
Getting rid of last remainings of old style string interpolation.
> Use f-strings instead of old style string interpolation

- .pre-commit-config.yaml
- locust/log.py
- locust/runners.py
- poetry.lock
- pyproject.toml
Unpin `poetry`:  `ruff` is pinned to one particular version to keep the same version as in .pre-commit-config.yaml. I don't see reasons for poetry to be pinned. (Especially since adding poetry.lock file to the repo).
Bump `ruff`: there were a lot of improvements over the last half year (including better detection of old style string interpolation #2974).
> Update ruff mypy

- examples/add_command_line_argument.py
- examples/web_ui_auth/custom_form.py
- locust/argument_parser.py
- locust/test/test_parser.py
- locust/web.py
- locust/webui/src/components/Form/CustomInput.tsx
- locust/webui/src/components/Form/PasswordField.tsx
- locust/webui/src/types/form.types.ts
- Using browser required fields makes it so the form may not be submitted without certain forms containing values. This will allow for extra options and more importantly fields in the auth form to be set as required
- MUI also visually displays the fields as required:
> Add option for Extra Options to be Required

- docs/developing-locust.rst
- docs/extending-locust.rst
- examples/web_ui_auth/custom_form.py
- locust/web.py
- locust/webui/src/components/Form/CustomInput.tsx
- locust/webui/src/types/form.types.ts
- Add a "type" field that can be used for HTML field validation (in this case email is what we mostly care about)
- Update docs
> Add Input Type to Login Form

- docs/configuration.rst
As dicussed in the issue #2987 a minimalistic  eample of config would prevent a reoccurence
> Update configuration.rst to show minimalistic config example

- docs/custom-load-shape.rst
Example is broken. It's just missing the `self.`
> Fix example in docs

- locust/web.py
- locust/webui/auth.html
- locust/webui/src/pages/Auth.tsx
(also adds an update to allow for overriding the title of the auth page)
> Allow showing auth info on blank page

- locust/webui/eslint.config.mjs
- locust/webui/src/hooks/tests/useFetchStats.test.tsx
- locust/webui/src/hooks/useFetchStats.ts
Fixes #3000 
The problem here was that was that updating the stats was happening at the same time as the fetch for stat data. So the UI was being updated with stale data, and when the new stat data would come in, the state would be updated immediately, but not the rest of the UI. The solution is to wait for the new stat data to be fetched, then update the entire UI
> Number of requests lower than expected in web UI

- locust/main.py
- locust/test/test_main.py
... and shut down locust right away
> Treat exceptions in init event handler as fatal

- locust/contrib/fasthttp.py
Relates to https://github.com/python/cpython/issues/95031
> FastHttpUser: Fix ssl loading performance issue by avoiding to load certs when they wont be used anyway

- pyproject.toml
got back from christmas vacation and rebuilt our framework that uses locust as a library for the first time, and running it failed:
```
master-1  |     from locust.event import EventHook
master-1  |   File "/venv/lib/python3.12/site-packages/locust/__init__.py", line 24, in <module>
master-1  |     from ._version import version as __version__
master-1  | ModuleNotFoundError: No module named 'locust._version'
```
scratching my head abit, but realised it thought it was probably related to `poetry-dynamic-versioning`, so saw that there had been a new release 2025-01-04, but in `pyproject.toml` this has been pinned with `<2.0.0`, but `poetry-core` had a broader constraint and a 2.x version had been released 2025-01-04 as well.
looking through the commit history I found: …
> pin poetry-core version to <2.0.0 in pyproject.toml

- locust/test/test_log.py
locust.test.test_log was broken locally for me as test_log was looking at the fqdn instead of hostname. To match this change: https://github.com/locustio/locust/pull/2705
```
test_logs: commands[0]> python -m unittest -f locust.test.test_log
.F
======================================================================
FAIL: test_log_to_file (locust.test.test_log.TestLoggingOptions.test_log_to_file)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/ajtuquero/Code/locust/locust/test/test_log.py", line 191, in test_log_to_file
self.assertIn(
~~~~~~~~~~~~~^
f"{socket.gethostname()}/INFO/locust.main: Run time limit set to 1 seconds",
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
log_content, …
```
> Update tests to check for hostname instead of fqdn

- Dockerfile
Python 3.13 is supported since version 2.32, but the base image was still based on 3.11.
> Update Dockerfile to use Python 3.12 as base

- README.md
- docs/quickstart.rst
Since v2.32.2, the new images have been added to the project, but the `quickstart.rst` still uses the old ones, Which causes the images not to be shown.
> fix readme image ref links

- locust/webui/src/hooks/tests/useSortByField.test.tsx
- locust/webui/src/hooks/useSortByField.ts
Small fix to allow tables to be set back to empty when filtering
> Allow Empty Tables when Filtering

- examples/custom_shape/wait_user_count.py
- examples/dispatch_test_scripts/locustfile.py
- examples/events.py
- examples/extend_web_ui.py
- examples/manual_stats_reporting.py
- examples/mongodb/locustfile.py
- examples/postgres/locustfile.py
- examples/terraform/aws/plan/basic.py
- examples/web_ui_cache_stats.py
- locust/__init__.py
- locust/argument_parser.py
- locust/contrib/fasthttp.py
- locust/html.py
- locust/main.py
- locust/rpc/__init__.py
- locust/test/test_fasthttp.py
- locust/test/test_load_locustfile.py
- locust/test/test_main.py
- locust/test/test_parser.py
- locust/test/test_sequential_taskset.py
- locust/test/test_wait_time.py
- locust/test/test_web.py
- locust/test/test_zmqrpc.py
- locust/user/__init__.py
- locust/web.py
- pyproject.toml
As any developer I am a little bit lazy from one side, and do not like pycharm warnings from another. 
Looking to locust internals I discovered, that there are a lot of places where unused imports exist and related check switched off in linting. This is not good practice, as it can lead to patch problems in some projects. So this PR fixes this problem and switch on related check.
Some required unused imports are excluded with noqa mark.
> Code quality: Fix unused imports and switch on related ruff check

- docs/configuration.rst
adds the missing `HISTORY_STATS_INTERVAL_SEC` option and the default values
> Update docs for stats.py file

- pyproject.toml
Removes `uv.lock` from build artifacts
Addresses behaviour described in https://github.com/locustio/locust/issues/3053
> Remove uv lock file from build artifacts

- docs/running-in-debugger.rst
- locust/contrib/fasthttp.py
Hey, I was wondering if we can extend the locust defaults for Accept-Encoding header with `brotli` and `zstd` to get closer to what modern browsers do:
* Safari: gzip, deflate, br 
* Firefox: gzip, deflate, br, zstd
* Chrome: gzip, deflate, br, zstd
Underlying python requests libs handle them well, I tested this by overwriting the header.
> FastHttpUser: Accept brotli and zstd compression encoding

- locust/argument_parser.py
- locust/html.py
- locust/main.py
- locust/test/test_html_filename.py
- locust/test/test_main.py
Here is an example:
locust --headless -u 12 -r 10 -t 10s --host http://127.0.0.1:8000 --html "{u}\_{r}\_{t}\_locust.html"
This would generate a filename:
12_10_10_locust.html
I use locust a lot at work, and in order to keep track of various test conditions among all the report files, I would manually update the filename. With this change, the file names can be more indicative of what the test was for. I would also consider adding P50, avg, etc...
Add HTML filename parsing
Add usage details to help command (The generated output is used in the docs)
Add tests
Put up a [PR previously](https://github.com/locustio/locust/pull/3005), but it was closed as stale. I've added tests and updated the help menu to contain usage information as well as an additional example.
> Enable HTML Report Filename Parsing

- docs/developing-locust.rst
Fix incorrect path in virtual environment activation command (.venv/bin.activate -> .venv/bin/activate)
> dos: correct venv activation path in docs

- docs/increase-performance.rst
- docs/running-in-debugger.rst
- locust/clients.py
Replace outdated python-requests URLs (python-requests.org) with current documentation URL (requests.readthedocs.io) in various documentation files and source code.
source: https://github.com/psf/requests/pull/5236
> docs: update python-requests documentation links

- locust/contrib/fasthttp.py
This commit introduces `params` and `files` attributes to the PostKwargs class in fasthttp.py, enhancing static type analysis capabilities without affecting existing functionality.
These additions ensure more precise argument definitions for methods in FastHttpSession.
> Fix missing optional argument definitions in PostKwargs

- locust/main.py
- locust/test/test_load_locustfile.py
- locust/util/load_locustfile.py
Continue to work on #3099 
This PR includes the following changes:
1. Change of `load_locustfile` function output objects. This is internal API change, but still should be released as next version, for example 2.36.0
2. Move merge locustfiles objects to separate function in main.py
3. Fix old incorrect typing in `load_locustfile` function in load_locustfile.py. It is interesting why mypy do not complain earlier.
Note: I leaved TODO message. Incorrect typing of User.tasks attribute is one of the reason I looked at main, the second one is incorrect help work (for command line objects). But correct .tasks attribute type rewrite will trigger many errors in different places, and will require additional tests. So not included at this point. It is in long 'todo' list, that out of my several …
> Refactoring: Extract locustfile content merger from main function

- locust/webui/src/components/SwarmForm/SwarmForm.tsx
The swarm form can now accept an array of custom inputs as `advancedOptions` to be displayed in the web ui
> Web UI: Optionally Extend Advanced Options

- locust/webui/src/components/Form/Form.tsx
Small fix / enhancement where form inputs without a name will not be included in the form data
> Web Ui: Ensure form element has name

- locust/webui/src/components/StateButtons/ResetButton.tsx
- locust/webui/src/components/StateButtons/StopButton.tsx
- locust/webui/src/components/StateButtons/tests/ResetButton.test.tsx
- locust/webui/src/components/StateButtons/tests/StopButton.test.tsx
- locust/webui/src/redux/api/swarm.ts
Allows us to have the baseUrl logic in one place, and ensures credentials are passed correctly should they be included
> Web UI: Use mutations for state buttons

- locust/stats.py
- locust/test/test_main.py
> Fix --json-file (actually save data to file)

- locust/web.py
With the following pathological locustfile, the following change hugely reduces the time it takes to call the `/stats/requests` endpoint.
```python
import uuid
from locust import FastHttpUser, between, task 
class User(FastHttpUser):
wait_time = between(1, 5)
@task
def call(self):
self.client.get(
f"/some-endpoint?a={uuid.uuid4()}",
json=None,
)
``` 
With the existing code, the endpoint almost immediately takes >100ms to execute:
Whereas with this branch, it stays around 50ms consistently:
Fixes #3134
> Fixes #3134 - Improve the performance of the `/stats/requests` endpoint

- docs/configuration.rst
- locust/web.py
- locust/webui/src/components/SwarmForm/SwarmForm.tsx
- locust/webui/src/test/mocks/swarmState.mock.ts
- locust/webui/src/types/swarm.types.ts
1. Show a warning if no host can be detected (e.g. no host flag is set and at least one http user is missing a host)
2. Add a configuration variable that allows for making the host required from the webui
> Webui: Warn on Missing Host

- pyproject.toml
- uv.lock
> Bump locust-cloud dependency, allow 25.x versions of gevent

- locust/contrib/fasthttp.py
Because it isn't actually supported by geventhttpclient.
Solves ValueError: Unknown content encoding: zstd
> FastHttpUser: Dont send zstd in Accept-Encoding header 

- Dockerfile
- Dockerfile.ci
Hi,
it was a long time ago since Python 3.13 was released (back in October 2024). So maybe it's time to release locust Docker image with Python 3.13 maybe.
Feel free to comment if I should change some Python version in CI or elsewhere.
Thanks for review.
> Update Dockerfile base to Python 3.13
